enzymejs/enzyme

.travis.yml
install-relevant-react.sh
package.json

to: @ljharb 
Get's travis working with coverage. 
Changes:
- Add missing params to pass into mocha
- add node 5 to the travis file
- fix the install-relevant-react file

fix npm travis script

---

README.md

to: @ljharb 
Adds status badges to readme

Add status badges to Readme.md

---

README.md
docs/api/mount.md

to: @ljharb 
Fixing issue https://github.com/airbnb/reagent/issues/39

Fixed incorrect documentation with .click() calls

---

docs/api/ReactWrapper/update.md

http://airbnb.io/enzyme/docs/api/ReactWrapper/update.html
I will try to aggregate these miniature changes in less PRs in the future.

Fix code tags in ReactWrapper update docs

---

README.md

Just to make sure that `sinon` was properly imported in the example code.
```
it('simulates click events', () => {
const onButtonClick = sinon.spy();
const wrapper = shallow(
<Foo onButtonClick={onButtonClick} />
);
wrapper.find('button').simulate('click');
expect(onButtonClick.calledOnce).to.be.true;
});
```

Updating the example to import `sinon`

---

docs/api/mount.md

Fix the link pointing to `ref()`'s docs

Fix wrong link

---

docs/api/ReactWrapper/instance.md
docs/api/ShallowWrapper/instance.md
docs/api/ShallowWrapper/update.md

Adds some missing backticks to the documentation.

Close code blocks in docs

---

src/ReactWrapper.js
src/__tests__/ReactWrapper-spec.js

Provides a descriptive error when simulating non-existent events

---

docs/api/ShallowWrapper/contains.md

Fix unfinshed sentence in ShallowWrapper.contains() doc

---

docs/README.md
docs/api/shallow.md

Add to sitemap and shallow docs

---

docs/guides/karma.md

Fixed typo in docs/guides/karma

Fixed typo in docs/guides/karma

---

docs/api/mount.md
docs/api/shallow.md

Add missing dots before method names in docs

Add missing dots before method names in docs

---

docs/guides/webpack.md

fix docs typo

---

docs/guides/jest.html

Fix jest typo in docs

---

docs/guides/jsdom.md

There is no need in this line `documentRef = document;`

remove strange assignment

---

src/ReactWrapper.js

This solves #223 
Not sure if we want to be linking to the docs from the code though?
What are peoples thoughts on this?

Dom not found error to explain that jsdom needs to be initialised before using mount

---

docs/api/ReactWrapper/contains.md
docs/api/ShallowWrapper/contains.md

Remove unused 
```
const passes = [		
<span>Hello</span>,		
<div>Goodbye</div>,		
];
```

Documentation, remove unused code

---

INTHEWILD.md

Adding Product Hunt to the enzyme in the wild list. :heart_eyes_cat: 
cc @ayrton

Adding Product Hunt to enzyme in the wild!

---

CHANGELOG.md

I think this is a little helpful :wink:

Documentations, issue numbers in CHANGELOG get linkable

---

CHANGELOG.md

Thank you for 2.1.0 release :tada:

 Documentations, fix release date of 2.1.0 in CHANGELOG

---

README.md

Just a missing backtick :smile:

add missing backtick to readme

---

src/Debug.js
src/Utils.js
test/ReactWrapper-spec.js

to: @ljharb 
cc: @ryanalane
This is essentially a copy of #220 . (There's a line or two different and that PR currently has conflicts).
Apologies to @ryanalane for stealing his git thunder :/
Fixes #134 
Closes #220

Fix props and debug methods for SFCs

---

test/ShallowWrapper-spec.js

Additional tests for SFCs written for `shallow`. Still figuring out how to proceed with `mount`.

[WIP] beef up tests for stateless function components

---

INTHEWILD.md

We love Enzyme here at Pinterest. Adding our name to the list of organizations! Nice work!

Adding Pinterest to organizations using Enzyme

---

INTHEWILD.md
README.md

Per @lelandrichardson on the tweettweet.
Add shoutout to `jasmine-enzyme` from README.md docs.
Also, adding Hudl to INTHEWILD

Add mention for `jasmine-enzyme`

---

docs/guides/webpack.md

ref https://github.com/airbnb/enzyme/issues/302

Documentation about react 15 and webpack usage

---

README.md
docs/guides/lab.md

- Adds guide on using Enzyme with Lab & Code.
- Links to example implementation; based on @lelandrichardson [enzyme-mocha-example](https://github.com/lelandrichardson/enzyme-example-mocha)

Adds documentation for using Enzyme with Lab

---

docs/api/mount.md

fix significant typo in function description

---

test/ShallowWrapper-spec.js

Add test cases for more types of HTML elements

---

docs/guides/browserify.md

Just a very minor typo I picked up on when using this awesome repo. Confused me for a split second.

Updated a typo in the browserify guide

---

src/ReactWrapper.js

NOTE: Documentation change only.

Fix documentation code example mistake

---

src/Utils.js
test/ReactWrapper-spec.js
test/ShallowWrapper-spec.js

Id selector not working when combined with a tag selector (#314)

---

docs/api/ReactWrapper/isEmpty.md
docs/api/ShallowWrapper/isEmpty.md
docs/api/mount.md
docs/api/shallow.md

Hi,
small PR for missing documentation for `isEmpty()` method.

Add missing docs for isEmpty()

---

docs/api/ReactWrapper/forEach.md
docs/api/ReactWrapper/map.md
docs/api/ShallowWrapper/forEach.md
docs/api/ShallowWrapper/map.md
test/ReactWrapper-spec.js
test/ShallowWrapper-spec.js

Addresses https://github.com/airbnb/enzyme/issues/366
Also added unit tests to cover the `index` parameter.

Add documentation and unit tests for index parameter for map and forEach methods

---

docs/api/ReactWrapper/context.md

Hi,
Just a small fix in a example of the doc. Not a big change but I spent 5 minutes trying to figure out why my code wasn't working so I figured someone else might have the same issue :)

Fix example in reactwrapper context doc

---

CHANGELOG.md

Super minor PR, simply noticed it while I was reading the changelog.

Fix syntax in enzyme changelog

---

INTHEWILD.md

Adds OpenGov as an org using Enzyme.

Add OpenGov

---

.eslintrc
src/MountedTraversal.js
src/ReactWrapper.js
src/ShallowWrapper.js
src/react-compat.js

This removes the warning overrides I added in f85d36cbc7dc53448b7051d1c4ac71c0e30f86b2 to unbreak master (my bad), and cleans up the linter rules a bit.

[Tests] clear up linter rules

---

src/ShallowWrapper.js
test/ShallowWrapper-spec.js

This PR is for to fix the issue https://github.com/airbnb/enzyme/pull/318#issuecomment-231311388 :bow:

Fix #318 shouldComponentUpdate is not called in shallow

---

INTHEWILD.md

Add Reapop to projects

---

docs/guides/webpack.md

Little typo

---

INTHEWILD.md

The use of enzyme is the official recommendation for react testing inside of GoDaddy.

Add GoDaddy to INTHEWILD.md

---

INTHEWILD.md

Adds Airware to the organization list.

Added Airware to organization list

---

docs/GLOSSARY.md

Linking to the actual Selector page

---

test/ReactWrapper-spec.jsx
test/ShallowWrapper-spec.jsx

This is a work in progress, since I'm stuck with a couple of case. Perhaps someone could help me with that? I skipped the two failing tests, I'll comment to explain my difficulties.

Remove arbitrary props from DOM elements

---

test/ShallowTraversal-spec.jsx

Looks like this snuck into master somehow. Travis shows the last few PR builds failing because of this.

fix lint error

---

src/ReactWrapper.jsx
src/ShallowWrapper.js
test/ReactWrapper-spec.jsx
test/ShallowWrapper-spec.jsx

Fixes https://github.com/producthunt/chai-enzyme/pull/118

[Fix] continue to support one-argument `single`

---

docs/GLOSSARY.md
docs/guides/systemjs.md

Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

Minor Fixes

---

docs/guides/jest.md

Correct README title typo to make it clear that the test below it is for Jest version 15+.

Correct README title

---

README.md

Mention [should-enzyme](https://github.com/rkotze/should-enzyme) custom assertions for should.js

Mention should-enzyme to readme

---

INTHEWILD.md

Hey. We're using enzyme while building the revamped version of our website. Good job everyone contributing !

Add crowdSPRING to 'in the wild'

---

docs/api/ReactWrapper/getNode.md
docs/api/ReactWrapper/getNodes.md
docs/api/ShallowWrapper/getNode.md
docs/api/ShallowWrapper/getNodes.md
docs/api/mount.md
docs/api/shallow.md

I updated docs because of #743 
@ljharb Can you check it?

Update Docs for .getNode and .getNodes #743

---

.github/ISSUE_TEMPLATE.md
docs/common-issues.md

To help our users and prevent duplicate issues I thought it would be nice to have a Github issue template that shows some common issues.

Create Common issues and issue template

---

INTHEWILD.md

Include nteract as a user of enzyme

---

INTHEWILD.md

Ref: https://github.com/brave/browser-laptop/blob/master/package.json#L144
🔥😎👍

🦁 Add Brave to the INTHEWILD list

---

docs/api/ReactWrapper/containsAllMatchingElements.md
docs/common-issues.md

corrected minor spelling errors in following files:
1. docs/api/ReactWrapper/containsAllMatchingElements.md
2. docs/common-issues.md

fixed typos in docs

---

docs/guides/jsdom.md

Added a link to reference JSDOM repository

Add a link to JSDOM repository

---

INTHEWILD.md

Simple uses Enzyme!

---

test/ShallowTraversal-spec.jsx

Catching a couple of the missing branches.

Additional tests for ShallowTraversal

---

INTHEWILD.md

Updated INTHEWILD.md

---

.github/ISSUE_TEMPLATE.md

Linking common issues in issue template.
Fix for [912](https://github.com/airbnb/enzyme/issues/912)
@blainekasten please review

Common issues link in issue template

---

INTHEWILD.md

We use enzyme to test cucumber.io/pro, and we 💯  it!

Add Cucumber to INTHEWILD.md

---

docs/guides/karma.md
docs/guides/webpack.md

Perhaps related issues:
- https://github.com/airbnb/enzyme/issues/940
- https://github.com/airbnb/enzyme/issues/968

[docs] Ensure `react-addons-test-utils` is set to `react-dom`

---

INTHEWILD.md

Added Genoa Telepsychiatry as a user of enzyme

Add Genoa Telepsychiatry to INTHEWILD.md

---

docs/guides/mocha.md

the example on the mocha guide wasn't working for me, so i searched around and found that i needed to add sinon.

added sinon to mocha guide

---

packages/enzyme/package.json

upgrade to rst-selector-parser@^2.2.2

---

docs/api/ReactWrapper/setProps.md
docs/api/ReactWrapper/setState.md
docs/api/ShallowWrapper/setProps.md
docs/api/ShallowWrapper/setState.md

suggest makeing param name same as what's in the side bar

make param name consistant

---

docs/api/ReactWrapper/setContext.md

missing "context."

---

packages/enzyme/package.json

Update rst-selector-parse to prevent issues in node 4

---

packages/enzyme-example-mocha/.babelrc
packages/enzyme-example-mocha/.eslintrc
packages/enzyme-example-mocha/.gitignore
packages/enzyme-example-mocha/.nycrc
packages/enzyme-example-mocha/LICENSE
packages/enzyme-example-mocha/README.md
packages/enzyme-example-mocha/package.json
packages/enzyme-example-mocha/src/Foo.jsx
packages/enzyme-example-mocha/src/Foo.spec.jsx
packages/enzyme-example-mocha/test/.setup.js

Mocha example project based on https://github.com/lelandrichardson/enzyme-example-mocha  
Updated versions of enzyme, react and jsdom and pulled project into the packages directory

Issue #965 - Added mocha example

---

README.md

- Add inferno-enzyme-adapter to README

[Docs] Add inferno-enzyme-adapter to README.md

---

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js
packages/enzyme-test-suite/test/Adapter-spec.jsx
packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
packages/enzyme-test-suite/test/_helpers/react-compat.js

Adding support for ReactDOM.createPortal

---

packages/enzyme/src/Utils.js

Use RSTTraversal childrenOfNode method in Utils
Closes #1380

[Refactor] Use RSTTraversal childrenOfNode in Utils

---

packages/enzyme-adapter-utils/src/Utils.js

Add event name mapping for transitionend

---

docs/api/ShallowWrapper/getElement.md
docs/api/ShallowWrapper/getElements.md
docs/api/shallow.md

Issue https://github.com/airbnb/enzyme/issues/1315

Add docs for getElement() and getElements()

---

env.js
packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js
packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx

cc @koba04 
Per https://github.com/airbnb/enzyme/pull/1453#discussion_r160019892
Failed: https://travis-ci.org/ljharb/enzyme/builds/325728918
Fixed: https://travis-ci.org/ljharb/enzyme/builds/325734315

15.4: Fix setState

---

docs/api/ShallowWrapper/setProps.md

Remove lifecycleExperimental reference from docs

---

INTHEWILD.md

[Cerner](https://github.com/cerner) is using Enzyme in our Terra open-source projects.

Add Cerner to INTHEWILD

---

docs/common-issues.md
docs/future.md

Just fixing a pet peeve of mine.

GitHub has a capital H

---

packages/enzyme-adapter-react-helper/package.json

Fixes https://github.com/airbnb/enzyme/issues/1639

Moving rimraf to dependencies

---

docs/guides/jest.md

Mention package.json on the Jest part of the docs

---

README.md
SUMMARY.md
docs/guides.md
docs/guides/karma.md

@ljharb asked me to update the Karma documentation with instructions on configuring Enzyme using an Enzyme setup file.
Closes #1257.

Documenting Enzyme configuration with Karma

---

docs/api/ReactWrapper/renderProp.md
docs/api/ShallowWrapper/renderProp.md
packages/enzyme-adapter-utils/src/wrapWithSimpleWrapper.jsx

I found some issues while reviewing #1863 after it was merged. This follow-up resolves them.
*If we accept #1891 we don't need to merge this PR as those fixes are contained in there as well.*

renderProp followup (doc corrections & console.log removal)

---

README.md

point `jasmine-enzyme` and `jest-enzyme`assertion library to the FormidableLabs

Update assertion library repo links

---

docs/api/selector.md

Update doc for display name

---

docs/api/ReactWrapper/reduce.md
docs/api/ReactWrapper/reduceRight.md
docs/api/ShallowWrapper/reduce.md
docs/api/ShallowWrapper/reduceRight.md

```
const total = wrapper.find(Bar).reduce((amount, n) => amount + n.prop('amount'));
```
In this example, total is an Object, because of there is no initial reduce value. we must set the initial value with 0 to get the right result.
And, the right result is 14.

[doc]fix error example

---

INTHEWILD.md

This sorts the list of organizations using a neutral alphabetical ordering and adds a company to the list.

Sort orgs list and add an entry

---

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx

Forgive me if this is not expected behavior.
This PR contains a failing test case that I believe describes the core of the issue at #2009.

Failing test for shallow context propagation

---

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
packages/enzyme-test-suite/test/shared/hooks/useDebugValue.jsx
packages/enzyme-test-suite/test/shared/hooks/useImperativeHandle.jsx
packages/enzyme-test-suite/test/shared/hooks/useRef.jsx

This PR finishes items in #2011, including tests for `useRef`, `useImperativeHandle`, `useDebugValue`.

Add useRef, useImperativeHandle, useDebugValue tests

---

packages/enzyme-adapter-react-helper/src/getAdapterForReactVersion.js

This is some minor cleanup of the work from #2116 and #2126 .

Consolidate version-tweaking logic into a single function

---

docs/api/ReactWrapper/update.md
docs/api/ShallowWrapper/update.md
docs/api/mount.md
docs/api/shallow.md

Fix the ReactWrapper#update and ShallowWrapper#update docs

---

README.md

Made license badge point to the respective file.

[Docs]: minor fix

---

docs/api/ReactWrapper/childAt.md
docs/api/ReactWrapper/children.md
docs/api/ReactWrapper/closest.md
docs/api/ReactWrapper/parent.md
docs/api/ReactWrapper/parents.md
docs/api/ShallowWrapper/childAt.md
docs/api/ShallowWrapper/children.md
docs/api/ShallowWrapper/closest.md
docs/api/ShallowWrapper/parent.md
docs/api/ShallowWrapper/parents.md
docs/api/mount.md
docs/api/shallow.md

Add missing arguments to selector description and related methods 

---

README.md

Please see image to known about PR:

[Docs] fix syntax in readme

---

docs/api/ReactWrapper/update.md
docs/api/ShallowWrapper/update.md

made a clarification on using update() method.

[Docs] `mount`/`shallow`: `update`: improve example

---

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js
packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx

I fixed https://github.com/enzymejs/enzyme/issues/2434 issue and add this case to tests.
Thanks for review!

Invalid suspense instance

---

docs/api/ReactWrapper/equals.md
docs/api/ReactWrapper/every.md
docs/api/ReactWrapper/everyWhere.md
docs/api/ReactWrapper/first.md
docs/api/ReactWrapper/instance.md
docs/api/ReactWrapper/matchesElement.md
docs/api/ReactWrapper/render.md
docs/api/ReactWrapper/simulate.md
docs/api/ReactWrapper/type.md
docs/api/ShallowWrapper/equals.md
docs/api/ShallowWrapper/every.md
docs/api/ShallowWrapper/first.md
docs/api/ShallowWrapper/render.md

Regarding the conversation from #2367 , I open the PR for the changed I made for refining some text, typo errors, and failing tests.

Update the API docs

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
INTHEWILD.md
README.md
docs/api/mount.md
docs/api/render.md
docs/guides/browserify.md
docs/guides/jest.md
docs/guides/jsdom.md
docs/guides/migration-from-2-to-3.md
docs/guides/react-native.md
packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
packages/enzyme-test-suite/test/Utils-spec.jsx

This PR fixes a few typos and 2 broken links I spotted. I also improves other links and changes various links from `http` to `https` protocol.

Fixing typos
