.eslintrc, .travis.yml
This tests more things and improves the travis.yml file. It also runs linting when it runs coverage, which it only does on one node build (currently 4.2, the LTS one).
=> Improve travis

docs/api/shallow.md
to: @lelandrichardson 
`.get()` returns a `ReactElement` and not a `ShallowWrapper`; the title in the docs indicated the former. Let's fix that!
=> Fix the title for .get() in the docs

docs/api/ReactWrapper/reduceRight.md
Example contains `reduce` rather than `reduceRight`.
=> Fix reduceRight documentation

docs/api/ShallowWrapper/type.md
=> Fix typo on Shallow Rendering type() example

src/index.js
=> Tweak the describeWithDOM label

src/ReactWrapper.js, src/ReactWrapperComponent.jsx, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowWrapper-spec.js, src/__tests__/_helpers.js
to: @ljharb @goatslacker 
Adds support for [stateless functional components](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components).
Brought up in https://github.com/airbnb/reagent/issues/45
Functional components cannot be a ref, and thus the "wrapper component" did not work with them.
Note that functional components are only available in react 0.14, so the tests for them are only run for react 0.14...
=> Support for Stateless Components

src/ShallowTraversal.js, src/__tests__/ShallowWrapper-spec.js
to: @ljharb @goatslacker 
The spec that was added in this PR would succeed in React 0.13 but fail in React 0.14 due to some changes in behavior from the two. This had been abstracted away for some selectors (like class name) through the correct `propsOfNode(node)` function, but the `nodeHasId` function was still prone to these issues. 
Thanks to @clouddra for pointing out.
Fixes https://github.com/airbnb/enzyme/issues/64
=> [bugfix] nodeHasId has issue with 0.14 in some cases

src/__tests__/ShallowWrapper-spec.js
According to the docs, it should be possible to `find` an element based on its display name. I simply added a test to assure that.
=> Added test for find by display name

docs/README.md, docs/api/ReactWrapper/ref.md, docs/api/mount.md, src/__tests__/ReactWrapper-spec.js
This PR fixes #86.
The method `.ref(refName)` already exists, but it was not documented in the API documentation.
I created a new page for `.ref(refName)` and added a test for it in `src/__tests__/ReactWrapper-spec.js` just to assure that the provided examples in the documentation are working.
=> Add .ref(refName) to the documentation

docs/api/ShallowWrapper/forEach.md, docs/api/ShallowWrapper/simulate.md
- Fix typos in ShallowWrapper/forEach docs example
- Fix ShallowWrapper/simulate docs example. Was simulating on wrong node (Fixes #88)
=> Minor Doc Fixes for ShallowWrapper.{forEach, simulate}

package.json
This allows versions of node <= 0.12.0 to use this project as jsdom 4.X > require node 4.X >
Issue: https://github.com/airbnb/enzyme/issues/94
=> CHANGED: The jsdom dependency to allow a range of supported versions.

README.md, docs/api/ReactWrapper/contains.md, docs/api/ReactWrapper/every.md, docs/api/ReactWrapper/everyWhere.md, docs/api/ReactWrapper/forEach.md, docs/api/ReactWrapper/hasClass.md, docs/api/ReactWrapper/is.md, docs/api/ReactWrapper/parent.md, docs/api/ReactWrapper/setProps.md, docs/api/ReactWrapper/some.md, docs/api/ReactWrapper/someWhere.md, docs/api/ShallowWrapper/contains.md, docs/api/ShallowWrapper/every.md, docs/api/ShallowWrapper/everyWhere.md, docs/api/ShallowWrapper/hasClass.md, docs/api/ShallowWrapper/is.md, docs/api/ShallowWrapper/parent.md, docs/api/ShallowWrapper/setProps.md, docs/api/ShallowWrapper/some.md, docs/api/ShallowWrapper/someWhere.md, docs/api/mount.md, docs/api/shallow.md, src/ReactWrapper.js, src/ShallowWrapper.js, src/__tests__/.eslintrc, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowTraversal-spec.js, src/__tests__/ShallowWrapper-spec.js, src/__tests__/Utils-spec.js
This enables the `no-unused-expressions` ESLint rule and fixes the corresponding violations. In fixing the errors I stumbled upon two tests that were broken. After discussing with @lelandrichardson, I've inverted the test case as the current behavior is the desired behavior.
Fixes #97
=> Enable no-unused-expressions ESLint rule

package.json, src/ReactWrapperComponent.jsx, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowWrapper-spec.js
Fixes https://github.com/airbnb/enzyme/issues/69
=> Normalized setProps behavior between mount/shallow

docs/api/shallow.md
Previously the link to `someWhere(predicate)` was pointing to `/docs/api/ShallowWrapper/someWHere.md`. 
I have changed to `/docs/api/ShallowWrapper/someWhere.md`.
=> Fix broken docs link

docs/api/ReactWrapper/find.md, docs/api/selector.md, src/MountedTraversal.js, src/ShallowTraversal.js, src/Utils.js, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowTraversal-spec.js, src/__tests__/ShallowWrapper-spec.js, src/__tests__/Utils-spec.js
Per discussion in #4 and continued discussion here. This PR adds support for querying react properties, and not html attributes. The following syntax works:
* `component.find('input[type="text"][value="1"])`
* `component.find('label[htmlFor="button"]')`
* `component.find('div[data-wrapper]')`
=> Support Property Selector

docs/README.md, docs/api/ReactWrapper/html.md, docs/api/mount.md, src/ReactWrapper.js, src/__tests__/ReactWrapper-spec.js
Hope I was on the right track, this is for #31
=> Add method, tests, and docs for html method in ReactWrapper

src/ReactWrapper.js, src/Utils.js, src/__tests__/ReactWrapper-spec.js, src/__tests__/Utils-spec.js
React camelcases a bunch of events that JS has in all lower case. This
PR adds a map of them so people can call `simulate` with either the
React version or the native event version.
Fixes #29.
Thought I'd take a stab at the fix - let me know what you think!
=> Map lowercase mouse events in #simulate

src/ShallowWrapper.js, src/__tests__/ShallowWrapper-spec.js
Resolves https://github.com/airbnb/enzyme/issues/119.
=> Fix `ShallowWrapper.setProps` not passing old context.

docs/api/ReactWrapper/find.md, docs/api/ShallowWrapper/find.md, docs/api/selector.md, package.json, src/MountedTraversal.js, src/ShallowTraversal.js, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowWrapper-spec.js
@blainekasten, thanks for quoting me in #105, gave me the drive to attempt to add the support. Let me know what you guys think.
I also just happened to notice while I tried to follow code patterns adding functionality that there seems to be some opportunity to reuse some code between `MountedTraversal` and `ShallowTraversal`. There was definitely some `copy & paste` I did :)
=> add support for object property selector

src/MountedTraversal.js, src/ShallowTraversal.js, src/Utils.js, src/__tests__/ShallowTraversal-spec.js, src/__tests__/ShallowWrapper-spec.js, src/__tests__/Utils-spec.js
to: @lencioni @ljharb @blainekasten 
When users were passing in selectors with a non-quoted string such as `[type=foo]` it was causing undesired behavior, matching any component that had the `type` prop.  This refactors the logic so that if the string is unquoted (and not an acceptable numeric literal or boolean), we throw a helpful error indicating that it should be quoted.
Fixes #127; Closes #129
=> Fixed confusing prop selector behavior. Added helpful warning

docs/api/ShallowWrapper/equals.md, src/ShallowWrapper.js, src/__tests__/ShallowWrapper-spec.js
=> Add `equals` method to ShallowWrapper.

.babelrc, package.json, src/ReactWrapperComponent.jsx, src/react-compat.js
- tests pass with React 13 & 14
- npm run travis produces coverage
- npm link works
=> Update to babel 6 #78

docs/api/ReactWrapper/setProps.md
I think in this example the className attribute should contain the name prop rather than the state name.
=> Possible error in example.

src/Utils.js, src/__tests__/ShallowWrapper-spec.js
When using the ShallowHelper you could not use lowercase event names such as `keydown`. This is because the propsFromEvent function is expecting the camelcased version.
To fix run the event through mapToNativeEventNames.
=> Fix shallowwrapper not calling events with lowercase names

README.md
Mentions [chai-enzyme](https://github.com/producthunt/chai-enzyme) in the readme.
If you think the wording is wrong, feel free to suggest any other text and I'll be happy to change (or move to a different place).
We could even go stronger in wording if we want to push users more towards the usage of the library:
> For convenience functions implementated as Chai.js custom assertions install [chai-enzyme](https://github.com/producthunt/chai-enzyme).
=> Mention chai-enzyme in readme

src/Debug.js, src/__tests__/Debug-spec.js, src/__tests__/_helpers.js
Composite components without `displayName` property are output as `<Component />` now. Debug can rely of `name` property of component if it is a class or a function and output it as component name.
=> Make correct output for component name in debug

src/Debug.js, src/__tests__/Debug-spec.js
Now we have strange `<undefined />` tag instead of child of number type. This PR should fix it.
=> Make correct output for number children in debug

src/ShallowWrapper.js, src/Utils.js, src/__tests__/ShallowWrapper-spec.js
Also I added a check for number:
```
it('should work with numbers', () => {
const wrapper = shallow(<div>1</div>);
expect(wrapper.contains(1)).to.equal(true);
expect(wrapper.contains(2)).to.equal(false);
});
```
=> fix #145 `contains` does not fail on string input

docs/README.md, docs/api/ReactWrapper/render.md, docs/api/mount.md, src/ReactWrapper.js, src/__tests__/ReactWrapper-spec.js
to: @goatslacker @ljharb 
Adds render method. pretty simple.
=> Add render method to ReactWrapper

docs/README.md, docs/api/ReactWrapper/detach.md, docs/api/mount.md, src/ReactWrapper.js, src/__tests__/ReactWrapper-spec.js, src/react-compat.js
to: @ljharb @goatslacker 
cc: @lencioni
Adds an optional API to render the components to a DOM element attached to the DOM. This will allow the user to test a couple of things they can't currently test such as focus state, computed style, etc.
=> attachTo option for mount/ReactWrapper

src/ReactWrapper.js, src/ShallowWrapper.js, src/Utils.js, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowWrapper-spec.js
Fixes #113.
^ @lelandrichardson, @goatslacker
=> [Fix] `{ShallowWrapper,ReactWrapper}#{type,props}()` should work with `null` nodes

src/ReactWrapperComponent.jsx, src/__tests__/ReactWrapper-spec.js
Let me know if there's a problem w this!
=> fixed setProps execption swallowing issue and added regression test

docs/api/shallow.md
=> Correct everyWhere(selector) API Documentation

docs/api/mount.md, src/ReactWrapperComponent.jsx, src/__tests__/ReactWrapper-spec.js
=> add option for childContextTypes of `ReactWrapper`

src/ShallowTraversal.js, src/__tests__/ReactWrapper-spec.js, src/__tests__/ShallowWrapper-spec.js
=> Prevent null or false nodes from being passed into tree traversal

docs/guides/jest.md
This commit adds 2 modules that should not be mocked by default in jest.
closes: https://github.com/airbnb/enzyme/issues/179
=> Update Jest docs

ReactWrapper.js, ShallowWrapper.js, mount.js, render.js, shallow.js, src/index.js, src/mount.js, src/render.js, src/shallow.js
This PR enables `require('enzyme/mount')`, `'enzyme/shallow'`, etc.
Fixes #195
=> Root-level file exports

docs/api/ShallowWrapper/type.md, src/ReactWrapper.js, src/ShallowWrapper.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
=> Ensure that `ShallowWrapper` and `ReactWrapper` handle a null child correctly

src/Utils.js
I think enzyme already switched from `underscore` to `lodash`.
```
➜  npm test
> enzyme@2.0.0 test /Users/koba04/github/enzyme
> npm run lint && npm run test:only
> enzyme@2.0.0 lint /Users/koba04/github/enzyme
> eslint src/**
> enzyme@2.0.0 test:only /Users/koba04/github/enzyme
> mocha --require withDom.js --compilers js:babel-core/register --recursive test/*.js
module.js:340
throw err;
^
Error: Cannot find module 'underscore'
```
=> Fix cannot find module 'underscore'

docs/README.md, docs/api/ShallowWrapper/unmount.md, docs/api/shallow.md, src/ShallowWrapper.js, src/react-compat.js, test/ShallowWrapper-spec.js
Shallow rendering has already supported since v0.13.
https://github.com/facebook/react/commit/e9e33b984fc022f68ec531826471fbd3a092e4b1
(It is not documented yet. https://github.com/facebook/react/pull/6086)
I think it would be great if enzyme supports this.
Thanks!
=> Add ShallowWrapper#unmount

INTHEWILD.md, README.md
The idea is that companies and/or projects can list themselves here, just like https://github.com/airbnb/javascript#in-the-wild,  https://github.com/airbnb/aerosolve/pull/103, and https://github.com/airbnb/airpal/pull/164.
It's in a separate file so that PRs to it don't have to touch the main README.
=> Add “In the Wild” section

docs/api/ShallowWrapper/filterWhere.md, docs/api/shallow.md
* The object returned from `shallow` is a `ShallowWrapper`, not `ReactWrapper`
* `complexFoo` is defined in an example in `filterWhere.md`, but `complexComponents` is asserted
=> Fix typos in shallow/ShallowWrapper docs

src/react-compat.js
A warning like this should hopefully help with #225.
Not exactly sure what the text should say.
=> Add warning about implicit dependency on react-addons-test-utils

src/MountedTraversal.js, src/ShallowTraversal.js, src/Utils.js, test/ReactWrapper-spec.js
Found and fix a mount issue with find when using a named component e.g. find('Foo')
Added test case to highlight the issue
fixed someone else's lint issues too
=> Found and fix a mount issue with find

src/Utils.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
moved checker to another line to make linter happy
=> Changed tests to highlight a bug with contains, fixed the bug in Utils/containsChildrenSubArray

docs/guides/jest.md
We finally fixed the npm3 module resolution and we do transitive unmocking of dependencies now.
"react-dom" and "react-addons-test-utils" should be unmocked too, however they aren' part of either react or enzyme so I guess we can remove them from this list too.
=> Update jest.md for Jest 0.9

docs/guides/browserify.md
The 'Using Enzyme with Browserify' guide specifies that you should make browserify ignore a different set of files if using React 0.13, but these are the files that should be ignored if using 0.14 onwards.
=> Fixes version of React in Browserify guide

src/ShallowTraversal.js, test/ShallowWrapper-spec.js
Like [#151](https://github.com/airbnb/enzyme/issues/151)
I have a problem like below.
```js
test('component should have no children', t => {
const component = shallow(
<div>
{undefined}
{undefined}
</div>
);
t.same(component.children().length, 0) // This should be success, but fail since length is 1.
});
```
I expect `null`, `undefined` and `false` should not be counted as a child node.
What do you think??
=> Prevent falsy nodes from being counted as children

src/MountedTraversal.js, test/ReactWrapper-spec.js
Children method did not work with nested stateless component. It always returns [null]
This patch fixes it
=> Fix children() for stateless children

docs/guides/webpack.md
As in the Browserify guide: #247, the version of React used in the Webpack documentation is wrong, it should specify 0.14, rather than 0.13
=> Corrects version of react in webpack.md

docs/api/ReactWrapper/filterWhere.md
=> Fixing the example for filterWhere

src/ReactWrapper.js, src/ReactWrapperComponent.jsx, test/ReactWrapper-spec.js
=> Fix context method for SFCs

docs/installation/react-15.md, package.json
This changes the React 15 support scripts from using RC1 to using RC2. The docs have been updated as well.
=> Move React 15 support tests from RC1 to RC2

docs/README.md, docs/api/ShallowWrapper/shallow.md, docs/api/shallow.md, src/ShallowWrapper.js, test/ShallowWrapper-spec.js
I have just enhanced the `ShallowWrapper#shallow` to support the same `options` arg as the top level `shallow` method.
It is useful when your component is wrapped by an high-order component like the ones provided in popular Flux implementations : 
- http://fluxible.io/addons/connectToStores.html
- https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options
For example :
```javascript
class MyComponent {
[...]
}
MyComponent.contextTypes = {
foo: React.PropTypes.string
}
export default connectToStore(MyComponent, [], () => {
[...]
})
```
Then you can easily shallow render `MyComponent`:
```javascript
const context = {foo: 'bar'};
const wrapper = shallow(MyComponent).shallow({ context })
```
I added the same context tests of …
=> Add options to ShallowWrapper#shallow

src/MountedTraversal.js, src/Utils.js, test/ReactWrapper-spec.js
This fixes an issue where calling `.find` with an SFC constructor/function would fail to return instances of the the SFC in the tree.
This seems like a round-about way of getting at this. Is there a better way?
Fixes #262
=> Fix issue finding nested SFCs by constructor in mount

src/ShallowWrapper.js
Something got merged (upgrade to eslint I think) that made this start to fail. Fixes.
=> Make linter happy with confusing arrow

docs/api/selector.md
Introduction states there are three categories of selectors but four are listed.
=> Update enzyme selector docs

docs/guides/jest.md
Fixes issue #286
Under Jest, Enzyme fails to load due to its dependency 'Cheerio', which
requires its package.json file without specifying the '.json' file
extension. This can be mitigated by adding '.json' to the
mduleFileExtension Jest config item in a projet's package.json.
=> adds json to moduleFileExtensions in docs

docs/api/ShallowWrapper/closest.md
In the selector for the closest .bar, there was a missing quotation mark around the class name
=> Add missing quotation mark

src/Utils.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
=> Add `dblclick` to properly map the native event.

docs/api/ReactWrapper/tap.md, docs/api/ShallowWrapper/tap.md, src/ReactWrapper.js, src/ShallowWrapper.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
This is similar to underscore's `tap()`.
http://underscorejs.org/#tap
When I'm testing complex React Element tree using method chains, I sometimes would like to inject a debug code between the method chains.
```js
wrapper
.find('.foo')
.findWhere(n => n.text() === 'bar')
// ???
.at(0)
```
* Using `tap()`
```js
wrapper
.find('.foo')
.findWhere(n => n.text() === 'bar')
.tap(n => console.log(n.debug())
.at(0)
```
* without `tap()`
```js
wrapper
.find('.foo')
.findWhere(n => n.text() === 'bar')
.map(n => {
console.log(n.debug());
return n;
})
.at(0)
```
I think this is not an essential feature, but it would be nice if enzyme has it.
How do you think about this? :+1:? :-1:?
Thanks.
=> Add tap() into ShallowWrapper and ReactWrapper

src/ShallowTraversal.js, test/ShallowTraversal-spec.js, test/ShallowWrapper-spec.js
Currently, the following test is failed.
```js
const wrapper = shallow(
<div className="bax">
<div className="foo">
<div className="bar">
<div className="baz" />
<div>
<div />
</div>
</div>
</div>
</div>
);
expect(wrapper.find('.baz').parent().hasClass('bar')).to.equal(true);
```
This is because `pathToNode` returns trees which are including the sibling node.
This PR makes `pathToNode` return only nodes including the current node.
Thanks
=> Fix pathToNode with a sibling node which has children

.npmignore
I have a case where I need to compile node_modules with babel but because enzyme ships with its own babelrc, it breaks my babel setup. I don't think there is a reason why the babelrc needs to be part of the package, so let's remove it, maybe? :)
=> Remove babelrc from npm package.

CONTRIBUTING.md, docs/guides/browserify.md, docs/guides/karma.md
Deprecated CommonJS `react/addons` entry point was removed in React 15.
https://facebook.github.io/react/blog/2016/04/07/react-v15.html
resolves #325
=> Update docs to externalize react/addons for newer versions of React

docs/guides/webpack.md
I've updated doc regarding webpack and React 15, which came from the [advice here](https://github.com/airbnb/enzyme/issues/47#issuecomment-207498885).
What I had to do to get things working with webpack and React 0.14 was different than in the guide, and I wrote about it [here](https://github.com/airbnb/enzyme/issues/47#issuecomment-213032872). I did not include it in this PR due to not really understanding what's going on and if my solution is a universal one, but I think a better guide will make sure people don't abandon using enzyme because they feel it's too hard to set up.
=> Update doc regarding webpack and React 15

src/ShallowTraversal.js, test/ShallowTraversal-spec.js
React provides the ability to override a component's display name by
using the `displayName` property. When `displayName` is provided it
should take precedence over `name`. Prior to this pull request,
`displayName` would only ever be used if `name` is not present but it
should have been the other way around.
=> prioritize `displayName` over `name`

docs/api/ShallowWrapper/props.md
Fixes `.prop` method signature in "Related Methods"
=> Typofix in props.md

src/MountedTraversal.js, src/ShallowTraversal.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
Resolves https://github.com/airbnb/enzyme/issues/347
=> Ignore nonsignificant whitespace in selectors

docs/api/selector.md, src/ComplexSelector.js, src/MountedTraversal.js, src/ReactWrapper.js, src/ShallowTraversal.js, src/ShallowWrapper.js, test/ComplexSelector-spec.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
Issue #23.
Added support for descendent, >, ~, and +.
=> Contextual css selector

src/ReactWrapperComponent.jsx, test/ReactWrapper-spec.js
Resolves #356 
[`getPublicInstance` returns `null` for SFCs](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L1202)  and the `_renderedComponent` appears to be a wrapper component that doesn't actually have a `render` method. This causes `findDOMNode` to fail as it uses the `render` method to validate that an object is a React component.
This returns the internal `_instance` instead of returning `component` when `inst === null`. 
I was thinking of maybe doing `return component._instance || component` to be extra safe but it didn't seem to make a difference.
=> Return component._instance if getPublicInstance returns null

.travis.yml
Io.js is not maintained anymore, and v6 is the latest
(example of io.js not maintained: https://nodejs.org/en/blog/vulnerability/openssl-may-2016/)
=> Test on node v6

src/Utils.js, test/Utils-spec.js
=> equals should skip null and undefined nodes fix #151

src/ShallowWrapper.js, test/ShallowWrapper-spec.js
- `.instance` was missing the `root` check even though it was mentioned in the description above.
- `state` and `setState` don't make sense for functional components so they now throw if called on a functional component (error message like the `root` one)
- also added the existing error checking of `setContext` to `context`
=> added error checking for state, setState, context, instance methods on ShallowWrapper

docs/api/ReactWrapper/simulate.md, docs/api/mount.md, src/ReactWrapper.js
The signature was wrong because the underlying function from React TestUtils takes only 2 arguments.
There was no test to fix because we were testing only the first argument.
=> Fix mount::simulate() signature

src/ShallowWrapper.js, src/react-compat.js, test/ShallowWrapper-spec.js
This PR is for `ShallowWrapper.simulate()` supports batched updates using `ReactUpdates.batchedUpdates`.
`React.addons.TestUtils.Simulate.{eventName}` is supporting batched updates.
ref. https://jsfiddle.net/koba04/6Lchbest/
`ReactUpdates.batchedUpdates` is exported as `ReactDOM. unstable_batchedUpdates` from React v0.14. In React v0.13, it is exported as  `React.addons.batchedUpdates`.
It might be better I use the exported interface.
But I guess it makes your configurations complex than using `ReactUpdates.batchedUpdates` directly.
FYI: This batched updates feature is required #318.
Thanks.
=> ShallowRenderer.simulate supports batched updates

docs/guides/jest.md
The moduleFileExtensions option is to list the extensions Jest looks at. If you overwrite it to `json` it will not load `js` files and will not work. See https://github.com/facebook/jest/issues/1014#issuecomment-219900877
Also updated the paths to work better (because they are paths, not module names).
=> Update Jest docs.

README.md
This will let users who are looking for support know they can go to #testing in reactiflux for help, instead of just opening an issue first :)
=> Add Discord logo and link to testing channel

src/MountedTraversal.js, test/ReactWrapper-spec.js
This change allows `.find('[data-attr1]')` and `.find('[data-attr_foo]')` to match as expected.
According to the HTML5 data-* spec, digits are allowed in data-* attributes.
Additionally, this prevents matching of invalid attributes, such as `:foo`, `-foo`, or `123-foo`,
=> Support additional characters in attribute selectors

docs/api/ShallowWrapper/containsAllMatchingElements.md
Just a tiny typo: `mathcing` -> `matching`.
Thanks for making an awesome tool like Enzyme :+1:
=> Fix typo in containsAllMatchingElements.md

src/ComplexSelector.js, test/ReactWrapper-spec.js
selectors shouldn't be split by space, because selector itself can contain a space
Example: .find('div[data-foo="foo bar"]')
=> bug fix: getSeletors()

test/ReactWrapper-spec.js
- added test ensuring that props() returns props of the root node
- added tests for untested prop() method
~~@lelandrichardson can you confirm that this behaviour of returning the props passed to the root node instead of the props of rendered root node is indeed the desired behaviour?~~ nevermind, I see why it is like this
=> tests for mount#props() and prop()

test/ShallowWrapper-spec.js
- added test ensuring that props() returns props of the root rendered node, not props passed to composite root component
- added tests for untested prop() method
=> tests for shallow#props() and prop()

src/Debug.js, test/Debug-spec.js
closes #475 
could one of the other maintainers look at this to make sure this change actually makes sense?
=> fixes mount().debug() output with mixed children

test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
React 15 added support for SFCs that return null. I added tests for this scenario in mount and shallow to complement preexisting tests for class components that return null
=> add tests for SFCs that return null in react 15

src/MountedTraversal.js, test/ReactWrapper-spec.js
The property [className](https://developer.mozilla.org/en-US/docs/Web/API/Element/className) returns an object on some (possibly all?) SVG elements (despite stating in the linked documentation that it always returns a string. Maybe there is a different SVG implementation that I missed...). The object behaves under the interface [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString), which does not have method ```replace```. If you have an SVG element somewhere within the mounted component then, as it iterates during a find, it processes the SVG element and throws ```TypeError: classes.replace is not a function```.
I tested [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) and it behaves correctly for SVG elements and regular …
=> Switch to using classList instead of className

docs/README.md
On the documentation home page, the link to the Lab instructions should lead you to a web page, instead you get the option to download a markdown file.
This ensures the link points to the generated HTML by adding the Lab page to the table of contents. The build gives many similar errors  (`x contains an hyperlink to resource outside spine`), so if you think this fix is correct I could also go over the rest.
=> Fix broken link to Lab setup instructions.

src/ShallowWrapper.js, test/ShallowWrapper-spec.js
This is a feature request which is supporting all React Component Lifecycle methods.
This is including some breaking changes.
This implementation is working on progress, and no (tests is passed)
Does this make sense?
If you are interested in this PR, please give me your feedbacks.
I'd like to work on it 😄 
Thanks.
=> Support all Component Lifecycle methods in ShallowRenderer

README.md, docs/guides/systemjs.md
Related to #302, https://github.com/jspm/jspm-cli/issues/1875.
=> docs: add systemjs guide

docs/api/ReactWrapper/matchesElement.md, docs/api/ShallowWrapper/matchesElement.md
Hey! I found two very small typos in the docs. In both cases, `onst` should be `const`.
=> Typo in docs

README.md, docs/README.md, docs/guides.md, docs/guides/tape-ava.md
This adds an example of how to use enzyme with [AVA](https://github.com/avajs/ava).
=> docs: add AVA guide

src/ReactWrapper.js, src/ShallowWrapper.js, test/ReactWrapper-spec.js, test/ShallowWrapper-spec.js
Resolves https://github.com/airbnb/enzyme/issues/510#issuecomment-236721789 per @ljharb's recommendation.
=> Throw if some() is called on a root wrapper

CHANGELOG.md
Support for spaces in attribute selector values was added in 2.4.0 ([PR #427](https://github.com/airbnb/enzyme/pull/427)) but was not documented in the changelog.  It took me a while to sort out why my selectors `option[value="by Alice"]` were working in 2.4.1 but not 2.3.0 ([see my gradual realization here](https://github.com/code-dot-org/code-dot-org/pull/9830)).  I'm recommending this get added to the changelog to save others some time.
=> Document additional bugfix in 2.4.0

docs/guides/mocha.md
Example file: https://github.com/lelandrichardson/enzyme-example-mocha/blob/master/test/Foo-test.js
There's also `render` import in the file example, don't know what that's for, probably unused.
=> Add missing import statement in Mocha example

INTHEWILD.md
Adds `react-dates` as one of the projects that uses Enzyme.
=> react-dates in the wild

docs/api/mount.md, docs/api/shallow.md
- The link to `.someWhere` in mount.md was broken due to a capitalization error
- All of the other links were broken in the web version of the docs due to absolute paths (they did work w/in Github)
=> Fix broken links to API docs

.travis.yml
- speed up tests further by *really* only running linting once.
- mark failing react-native and karma-webpack example tests as "allowed failures", which were being previously skipped.
=> [Tests] Rewrite test matrix config

src/MountedTraversal.js, src/ShallowTraversal.js, src/Utils.js, test/ShallowTraversal-spec.jsx
Fixes #562.
I also consolidated some code.
=> Fix valid + falsy propvalues

docs/api/ShallowWrapper/parents.md
I just found the missing dot in docs, nothing serious.
=> Small typo fixed in docs

docs/guides/jsdom.md, withDom.js
I couldn't see any reason for the `exposedProperties` array in `withDom.js`. Seems to be redundant so this pull request removes it. 
/cc @lelandrichardson
=> Remove redundant `exposedProperties` array

src/Utils.js, test/ReactWrapper-spec.jsx, test/Utils-spec.jsx
We still don't support these, so we need to warn about them. Parsing this with a RegEx is really difficult so instead `isPseudoClassSelector` does some minimal pattern matching combined with some logic to only match cases where `:` is not within quotes.
cc @ljharb
=> Warn if selector contains a pseudo-class

docs/api/ShallowWrapper/prop.md, docs/api/ShallowWrapper/props.md
Fixes #397
As many others have stated, the documentation for .props & .prop(key) are fairly ambiguous on which props are being return for shallow wrappers. It's unclear that the props that are actually being returned are from the **parent element of the component**, since it's easy to mistakenly assume that `props()` would return the props you would recieve from a React component as with `this.props`
Changes proposed:
- Add notes to both `.prop(key)` and `.props()` documentation in the ShallowWrapper API warning newcomers about what **props are being returned & what props are not**
- Add references to `instance()` to show how to retrieve the instance props as with the usual React `this.props` pattern.
- Update examples for both pages to demonstrate the key difference between the props …
=> Add documentation note clarifying shallow wrapper prop functions

docs/api/ReactWrapper/html.md
I've been doing expect(wrapper.html()).to.equal(null) to force output, wrapper.debug() is easier.
=> Add link to debug()

docs/api/ShallowWrapper/dive.md, docs/api/shallow.md, src/ShallowWrapper.js, src/Utils.js, src/react-compat.js, test/ShallowWrapper-spec.jsx
The goal of this method is to make testing of HOCs (higher-order components) easier - [withStyles](https://www.npmjs.com/package/react-with-styles), flux-store-connected components, etc.
Typically, the workarounds are either:
- `wrapper.find('StringNameOfComponent').shallow()`: brittle, because it's using strings (strings are bad); also annoying to type out.
- `wrapper.childAt(0).shallow()`: doesn't check if there's more than one child, and is annoying to type out.
In addition, if suddenly there's a DOM element in there, you might suddenly start shallow-rendering it without knowing, and your tests might erroneously be passing.
This method allows `wrapper.dive()` - ie, it requires there be one non-DOM child, and shallow-renders it for you.
If you need multiples, you chain them - …
=> [New] `shallow`: add `.dive()`

src/ReactWrapper.jsx, src/ShallowWrapper.js, src/Utils.js, test/ReactWrapper-spec.jsx, test/ShallowWrapper-spec.jsx
Resolves https://github.com/airbnb/enzyme/issues/577
cc @ljharb
=> Make ReactWrapper and ShallowWrapper iterable

README.md
[`jasmine-enzyme`](https://github.com/blainekasten/enzyme-matchers) has expanded to become a monorepo supporting both jasmine and jest as independent packages. This updates the docs to point to the correct repo, and show the different options.
=> Add note about jest-enzyme matchers in README.md

docs/guides/jest.md
There was a question on Gitter about [using Enzyme with Jest](https://gitter.im/airbnb/enzyme?at=5813932183a2008d22e32837), and I noticed that the Jest guide was a little out of date. This PR updates that guide for Jest 15 and up.
The guide referenced a [sample test repo by Leland Richardson](https://github.com/lelandrichardson/enzyme-example-jest). Rather than ask him to manage updating the samples, I forked it and updated [my fork](https://github.com/vjwilson/enzyme-example-jest). This change references my updated fork.
I also left the his instructions for earlier versions of Jest that require mocking, just in case someone still has to use an earlier version.
=> Update instructions for Jest versions 15+

package.json, src/Debug.js, src/ShallowTraversal.js, src/Utils.js
This will make enzyme detect stateless components correctly also in
Internet Explorer.
=> Use shim to detect constructor function name.

package.json, src/Utils.js, test/ReactWrapper-spec.jsx, test/ShallowWrapper-spec.jsx
This fixes the unintentional breaking change in 2.4.x (and 2.5.x), by committing horrible sins with regular expressions. This also does not revert the new behavior added in 2.4.x (that caused the breakage).
We desperately need to replace this with a proper CSS parser, but this should suffice for now.
Once merged, I'll also backport this to the 2.4.x line (and 2.5.x if master already has some semver-minor stuff).
=> Fix ID selectors

docs/api/ReactWrapper/contains.md, docs/api/ReactWrapper/containsMatchingElement.md, docs/api/ShallowWrapper/contains.md, docs/api/ShallowWrapper/containsMatchingElement.md
To help with confusion from #652.
- Changes "looks like" wording to "matches".
- Changes descriptions of `contains()` to follow same structure as `containsMatchingElement()`. Also updates doc examples for both functions to make similar wrappers and assertions. The hope is to have the similarities between the docs help highlight the differences between the functions.
- Changes `contains()` docs to be plural given that `contains()` can accept an array of nodes.
- Changes examples to use native elements only (no `MyComponent`).
=> Clarify docs for `contains()` and `containsMatchingElement()`

src/MountedTraversal.js, test/ReactWrapper-spec.jsx
This (hopefully?) address the long running issue #134, where `wrapper.hasClass` always returns false on `mount`ed composite components. The reason for the failure is the following block in `MountedTraversal.js#instHasClassName`:
```js
if (!isDOMComponent(inst)) {
return false;
}
```
Simply removing this block breaks many things, as the method is used internally in `MountedTraversal.js`. My naive solution is to split the method in two, so we retain the exported `instHasClassName` function for use by `ReactWrapper.hasClass`, and extract a private `hasClassName` function for use internally in `MountedTraversal.js`.
From here we can remove the `!isDOMComponent` early exit code from `instHasClassName`, and instead add it to `hasClassName` to maintain existing functionality.
=> Make hasClass work for `mount`ed composite components

test/ShallowWrapper-spec.jsx
- test that componentWillReceiveProps is called in the right order when render is aborted in shouldComponentUpdate
- test that a 2nd re-render lifecycle works the same as the 1st one
=> more tests for lifecycleExperimental

withDom.js
Lost a bunch of time on this today because I thought it was a compatibility issue around the new `react@15.4.0` release ...
... instead of just my own error of forgetting to install `jsdom` in a new module. 🙀 🙀 🙀 
Hopefully this helps others avoid my mistake. Tried to make the message displayed to users as clear as possible. 💯 ✨ 👍 💪 😼 
_
> _Testability is tricky on this since the `enzyme` module itself depends on `jsdom` so the error will never be produced. I could introduce `proxyquire` and force `require('jsdom')` to throw, but that seemed like overkill. Hopefully the change is obvious and small enough._
=> Display a useful error when `withDom` fails to find "jsdom".

src/MountedTraversal.js, test/ReactWrapper-spec.jsx, test/ShallowWrapper-spec.jsx
Fixes #689.
- add `shallow` test just in case
- use `values` over `Object.keys` in MountedTraversal
=> [Fix] `mount`: ensure that `react-text` comment nodes don’t break `.find`

docs/api/ReactWrapper/getDOMNode.md, docs/api/mount.md, src/ReactWrapper.jsx, test/ReactWrapper-spec.jsx
As outlined in #623 and #446, implement `ReactWrapper#getDOMNode` which provides access to the outer most DOMComponent of a mounted composite component.
If you are happy for this to exist, I will add api documentation.
=> Get outer DOM node from composite component wrapper

src/MountedTraversal.js, src/ReactWrapper.jsx, test/ReactWrapper-spec.jsx, test/ShallowWrapper-spec.jsx
Actually, this is a bug report. Test should pass, but it doesn't.
When elements tree has more than one branch, `.parents()` method returns some nodes, which are not  parent of the element.
=> mount: fix broken `.parents()`

docs/guides/webpack.md
Webpack 2 changes what's allowed in the externals part of the config, so I updated the docs to have Webpack 1 and Webpack 2 examples.
The example WP2 change is what I use on a project and it all works just great.
=> Update webpack usage with Webpack 2

package.json
It is not necessary to include this module in `dependencies` as the `prepublish` lifecycle is not executed when enzyme is installed as a dependency of another package.
```shell
$ mkdir -p /tmp/foo
$ pushd !$
$ npm -v
3.10.10
$ npm init --yes
$ npm i --save react enzyme
$ rm -rf node_modules
$ npm i --loglevel=silly &> install.log
$ cat install.log | grep lifecycle | wc -l
418
$ cat install.log | grep lifecycle | grep prepublish
npm info lifecycle foo@1.0.0~prepublish: foo@1.0.0
npm sill lifecycle foo@1.0.0~prepublish: no script for prepublish, continuing
```
Identical results with npm `v4.0.3`
=> [Dev Deps] move `in-publish` to `devDependencies`

src/MountedTraversal.js, src/ReactWrapper.jsx, test/ReactWrapper-spec.jsx
PR #677 introduced a bug where calling `hasClass` on a component that renders `null` would throw an exception. This fixes that.
=> Fix bug introduced in #677

src/MountedTraversal.js, test/ReactWrapper-spec.jsx
Resolves https://github.com/airbnb/enzyme/issues/603
Currently React will return `null` for `_renderedChildren` if the only child is a text node. But if there is an actual DOM node as well, it will return that along with any sibling text nodes.
This change ignores text nodes when calling `wrapper.childen()` with `mount`. With `shallow`, no instances are actually needed when parsing children, so this works already. 
``` js
const wrapper = shallow(<div>B<span />C</div>);
const children = wrapper.children();
// children = ['B', <span/>, 'C']
```
So there's some inconsistency there. I think it makes more sense to let shallow return text nodes, but we could ignore them if we want consistency.
cc @ljharb
=> Ignore text nodes in childrenOfInstInternal

src/MountedTraversal.js, src/ReactWrapper.jsx, src/ShallowWrapper.js, src/Utils.js, test/ReactWrapper-spec.jsx, test/ShallowWrapper-spec.jsx, test/Utils-spec.jsx
This PR fixes the matching APIs.
`<div>` and `<div id={undefined} />` absolutely should match, because React, most of JS, and human intuition does not distinguish between "absent" and "undefined". This is inarguably a bug fix.
This PR also asserts that `<div>` and `<div id={null} />` should match. JS doesn't treat them this way - and React treats them differently only in the case of defaultProps. However, by the time `enzyme` is attempting to match elements, any defaultProps have been applied - and my contention is that absent a defaultProp, `null`, `undefined`, and "absent" should all be treated the same.
This came up specifically because I attempted to add missing defaultProps, set to `null`, on a component, and tests using enzyme's matching APIs began to fail. I don't believe they …
=> [Fix] mount/shallow: "match" should not differentiate nullary props

src/ShallowWrapper.js, test/ShallowWrapper-spec.jsx
I made it, could you check this source?
I only added a logic that merges options to `dive()`
refs: #770
=> [Fix] `dive` should pass along options from `shallow`

docs/api/selector.md
Just ran across this while browsing the docs.
[http://www.alphadictionary.com/articles/english_grammar_style/difference_between_its.html]()
=> fix typo, it's/its

src/ShallowWrapper.js, test/ShallowWrapper-spec.jsx
This PR is to fix #805.
When `lifecycleExperimental` is `true` and `shouldComponentUpdate` returns `false`, ShallowWrapper should update instances's props with passed props.
I've also added some unit tests for to assert updating `props` and `state` and `context` whether `shouldComponentUpdate` returns `true` or not.
=> Fix a bug that doesn't update props with lifecycleExperimental: true and sCU: false

INTHEWILD.md, src/Utils.js, test/Utils-spec.jsx
=> Match children before and after interpolation

README.md
Briefly mentions `expect-enzyme` with the other assertion libraries on the readme.
=> Add expect-enzyme library to readme

README.md
Examples were missing `expect` from chai.
=> Add missing imports

docs/api/ReactWrapper/matchesElement.md, docs/api/ShallowWrapper/containsAllMatchingElements.md, docs/api/ShallowWrapper/containsAnyMatchingElements.md, docs/api/ShallowWrapper/containsMatchingElement.md
I overlooked these methods and wasted a lot of time because I didn't read the docs carefully enough until I stumbled across this PR https://github.com/airbnb/enzyme/pull/362. Edits to make it more clear that they do matching with a limited subset of props specified on supplied element and other props will be ignored. 
Minor grammar/language improvements while I was at it.
=> [docs] Minor improvements to docs around matchesElement

docs/api/shallow.md, src/ShallowWrapper.js, test/ShallowWrapper-spec.jsx
As part of the plan to switch on all lifecycle methods for `shallow` in the next major, introduce a no-op flag ahead of time that turns that off.
Ref: https://github.com/airbnb/enzyme/issues/678#issuecomment-274949209
~~Since there's no options validation, I'm not sure any code changes are necessary.~~ (added) It may be confusing if someone sets this flag to explicitly false and expects their lifecycle methods to be called. Should we set lifecycleExperimental to true in that case?
I didn't prefix the option with `deprecated` because it seemed this flag is going to be sticking around as the official, inverted version of lifecycleExperimental. I may have misunderstood something though.
The name feels a bit off since it's not disabling *all* the lifecycle methods, just two of them. Should it …
=> add disableLifecycleMethods for shallow

src/Utils.js
Except in the most recent versions of node, developers are unable to delete
things from global when running code in a node vm.  This means that enzyme is
failing to clean up after itself when temporarily defining global.document for
setState calls.
This papers over the issue by explicitly setting global.document to undefined
if it failed to be deleted.
Relevant jest issue - https://github.com/facebook/jest/issues/3152
Relevant node pr - https://github.com/nodejs/node/pull/11266
=> Fix an issue w/ cleaning up global.document.

src/Utils.js, test/ShallowTraversal-spec.jsx
closes #794 
interim solution until we switch to a proper CSS selector solution
=> Throw for malformed compound selectors

src/Utils.js
For the purposes of testing an editor based on https://github.com/facebook/draft-js, I'd like to be able to simulate the `beforeinput` event.
I didn't see tests to make sure that each event is mapped properly, so I didn't add one. If I missed it, please point me the proper place, and I'm happy to add one.
Thanks for enzyme! It's fantastic!
=> Add beforeInput to simulated event map.

docs/api/ReactWrapper/matchesElement.md, docs/api/ReactWrapper/setContext.md, docs/api/ShallowWrapper/matchesElement.md, docs/api/ShallowWrapper/prop.md, docs/api/ShallowWrapper/props.md, docs/api/ShallowWrapper/setContext.md, docs/api/render.md, src/ReactWrapperComponent.jsx
In react@15.5, `React.createClass` is deprecated, So we have to use `create-react-class` instead. #876
In this PR, I've converted `React.createClass` to `React.Component` except some tests for `React.createClass`. 
Should Enzyme support `create-react-class`? If it isn't necessary, I can remove all `React.createClass` from the tests.
* https://github.com/airbnb/enzyme/blob/master/test/ReactWrapper-spec.jsx#L3270
* https://github.com/airbnb/enzyme/blob/master/test/ReactWrapper-spec.jsx#L3306
* https://github.com/airbnb/enzyme/blob/master/test/ShallowWrapper-spec.jsx#L1273
* https://github.com/airbnb/enzyme/blob/master/test/ShallowWrapper-spec.jsx#L3909
* https://github.com/airbnb/enzyme/blob/master/test/ShallowWrapper-spec.jsx#L3955
After this PR is merged, Enzyme can put …
=> Convert React.createClass to React.Component

docs/api/ReactWrapper/setContext.md, docs/api/ShallowWrapper/setContext.md, docs/api/render.md
Not sure if I should also include explicit imports in the `setContext` examples.
=> Update docs to use the prop-types package #890

src/ShallowWrapper.js, src/react-compat.js
Users with package.json files that include:
```
"react": "^15.4.0",
"react-dom": "^15.4.0",
"enzyme": "^2.8.0",
```
will have their tests break after https://github.com/airbnb/enzyme/pull/876.  This PR fixes it so enzyme "does the right thing" in the case where the user is running react 15.4, running react 15.5 but hasn't done any of the "upgrade work" yet, and in the case where they are actually running 15.5.
Verified by running [this test script](https://gist.github.com/jwalton/efda0a6d2b966fb8e6431f3fb864295b#file-test-sh).  If you want to run this, you need a folder called ~/Development/enzyme which has a built copy of this branch, and you need to run it in some other directory.  (Need the built copy instead of just `npm link`ing because we need to pick up the right versions from the …
=> Make enzyme work for react ^15.4.x.

src/react-compat.js
In some cases, the logging from console.error is swallowed (e.g. when
using create-react-app and having multiple test files). By placing the
message in the error instead, it is shown.
Before this change and without having `react-test-renderer` as a dependency, this message would be shown:
```
Cannot find module 'react-addons-test-utils' from 'react-compat.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
at node_modules/enzyme/build/react-compat.js:143:21
at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:214:5)
```
After this change, this is shown instead:
```
react-dom@15.5+ and react-test-renderer are implicit dependencies when using react@15.5+ with enzyme. Please add the appropriate version to your devDependencies. See …
```
=> Make sure dependency error reporting always works

src/Debug.js, test/Debug-spec.jsx
- Fixes #925, the issue where .debug() on a shallow wrapper does not indent child nodes
The problem is with the use of `.map()`:
```
export function debugNodes(nodes) {
return nodes.map(debugNode).join('\n\n\n');
}
```
[Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map?v=example) passes 3 args to the callback, the second of which is the current index (0 in this case since there's only one top-level node), which overrides the default arg value `indentLength = 2` in debugNode.
The fix here adds a callback that explicitly only takes one parameter and then calls debugNode explicitly with that single parameter: `nodes.map(node => debugNode(node))`
=> Fix #925 - indentation is broken for debug() on shallow wrapper

docs/guides/jsdom.md
Updated "jsdom" guides which is based on "jsdom" v10 and later API
`jsdom` has recently updated to v10, but the enzyme's guides is based on ["old-api"](https://github.com/tmpvar/jsdom/blob/master/lib/old-api.md). `jsdom` says it supports the old api yet, so I did not delete the old code block but instead add a new code block.
> The old API is still supported for now
Fixes #942.
=> [docs] Update "jsdom" guides for v10 and later

src/Debug.js, src/ReactWrapper.jsx, src/ShallowWrapper.js, test/Debug-spec.jsx
Implements #960. Adds options object to debug(). Uses options.ignoreProps to opt-in to ignoring props from the debug() string output. This change is backwards-compatible so existing usages of debug() are unaffected.
=> [enhancement] #960 allow debug() to exclude props

docs/api/shallow.md
In shallow rendering we do not call `componentDidMount`, this fixes the docs to reflect that.
=> Change componentDidMount to componentWillMount in shallow options api doc

package.json, src/Utils.js
=> Update uuid 2.x -> 3.x

package.json
In #998 I bumped uuid 2.x -> 3.x and converted the import to
import from `uuid/v4`, but this didn't exist until 3.0.1.
=> Require uuid at least 3.0.1

docs/api/shallow.md
In ShallowWrapper-spec.jsx line 2766 for testing disableLifecycleMethods option, when disableLifecycleMethods is set to true, componentWillMount is expected to be called, componentDidMount was the one not getting called. This contradict what's in shallow.md. I found this issue when I was using disableLifecycleMethods option and componentWillMount() always fires.
=> update shallow.md to describe disableLifecycleMethods option correctly

docs/api/shallow.md
As far as I know, the `options.lifecycleExperimental` is not documented yet.  
I just found this pull request https://github.com/airbnb/enzyme/pull/318 and that's the only place where we see that option
=> Update shallow docs with lifecycleExperimental

docs/api/ReactWrapper/mount.md, docs/api/ReactWrapper/setProps.md, docs/api/ReactWrapper/unmount.md, docs/api/ShallowWrapper/setProps.md, docs/api/ShallowWrapper/unmount.md, docs/api/shallow.md
**GOAL:**
I was reading through the API documentation and noticed that there were a few inconsistencies with imports of `sinon` and usage. I have added the explicit imports of `sinon` to the relevant places in the documentation. I believe this is a valuable addition because it will remove any ambiguity from the code examples.
**CURRENT:**
Currently, there are a couple of API docs where code examples are using `sinon` without an explicit import. The main docs page explicitly imports `sinon` and this change will make it consistent throughout all the docs.
**IMPACT:**
This will remove ambiguity from the docs and explicitly mention other dependencies for the code samples.
=> Adds Sinon imports to API docs.

docs/api/ShallowWrapper/setProps.md
As discussed here: https://github.com/airbnb/enzyme/issues/34 `setProps` does not trigger the `componentDidUpdate` lifecycle method by default.
I've updated the Common Gotchas section of the `setProps` documentation with the solution to set `lifecycleExperimental` to true.
=> [Docs] Update Common Gotchas for ShallowWrapper setProps

src/ShallowWrapper.js, src/Utils.js, src/adapters/ReactFifteenAdapter.js, src/adapters/ReactFifteenFourAdapter.js, src/adapters/ReactFourteenAdapter.js, src/adapters/ReactSixteenAdapter.js, src/adapters/elementToTree.js
* Removes usage of `isFunctionalComponent` which caused some problems when running tests with the production React bundles (see #1041)
* Fixes an issue where the shallow renderers were returning an incorrect `nodeType` for the root node. It was always returning `'class'` even when the component was functional.
=> Remove isFunctionalComponent, use nodeType instead

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.jsx, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js
to: @ljharb @aweary 
This is in preparation for Enzyme v3.0. We are moving properties that are considered private and implementation details to use symbols and harder to rely on property names in an effort to make future migrations easier.
=> Make private properties more private and harder to use

env.js, packages/enzyme-adapter-react-13/package.json, packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js, packages/enzyme-adapter-react-14/package.json, packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-15.4/package.json, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/package.json, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-adapter-utils/src/createMountWrapper.jsx, packages/enzyme-adapter-utils/src/createRenderWrapper.jsx, packages/enzyme/package.json, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js, packages/enzyme/src/render.js
to: @ljharb @aweary 
This PR removes all react dependencies from the core enzyme library. In order to do this, the component "wrappers" were moved from enzyme into the adapters. This ends up cleaning up a number of things, and I think worked out rather nicely.
=> Remove all React dependencies from enzyme

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
When shallow rendering a component with `lifecycleExperimental: true` the lifecyle methods `componentWillReceiveProps` and `shouldComponentUpdate` will only be called with the value given to `setProps`, but not with old and new props merged.
It works for shallow rendering without lifecycleExperimental.
Due to the "[dirty hacks](https://github.com/airbnb/enzyme/blob/da9140713a946ef3bef23952e693bc917166a0b3/packages/enzyme/src/ShallowWrapper.js#L272-L293)" i'm not sure if there is a better way to do this, but this at least fixes the dirty hacks.
=> props not merged when shallow rendering in lifecycleExperimental

packages/enzyme-adapter-utils/src/createMountWrapper.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
Fixes #1091.
Turns out that this was only an issue on class-based components (possibly SFCs as well), presumably because createClass clones `contextTypes` for us.
=> [Fix] `mount`: do not mutate `Component.contextTypes`

docs/api/ReactWrapper/reduce.md, docs/api/ReactWrapper/reduceRight.md, docs/api/ShallowWrapper/reduce.md, docs/api/ShallowWrapper/reduceRight.md, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
Closes #667.
I've marked this as a patch - but it might potentially be breaking if someone was relying on omitting the required (incorrectly documented as optional) initialValue being `undefined`.
Thoughts?
=> [Fix] `reduce`/`reduceRight`: follow `Array#reduce` when omitting initialValue

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/staticRender-spec.jsx, packages/enzyme/package.json, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/render.js
See https://github.com/cheeriojs/cheerio/issues/1047#issuecomment-325221409 for context.
Hoping to merge this ASAP so it can be part of v3.
cc @jugglinmike
This semver range also will include `^1.0.0` once it's released, verified on https://semver.npmjs.com/
=> [Deps] [breaking] update `cheerio` to v1

packages/enzyme-adapter-react-15/package.json, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js
This PR moves the enzyme-adapter-react-15 package from the "test utils" shallow renderer to the "react-test-renderer" shallow renderer. I believe this is running essentially the same exact code, but will not trigger a console.error when used.  I'm not sure how I missed this earlier.
=> Move adapter 15 to react-test-renderer

docs/api/mount.md
I was following the discussion at #911 and thought that this might be a useful note to add. I can also incorporate it in the example below if you want.
=> Add note that mount() requires cleanup

.travis.yml
Adding this in temporarily since karma is sporadically failing. I'm investigating the fix, but for now I don't think we should mark these as required
=> Add karma tests to allowed failures

packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme/package.json
In response to #1124, which was resolved by https://github.com/aweary/rst-selector-parser/pull/5. I published it as a patch release which matches our Semver range for that dependency.
This just adds a small test to prevent regressions on this. There's also a test in `rst-selector-parser` for this, so we get double the coverage.
=> Add test for querying components wrapped with HOCs

packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
This adds a public `root()` method to the shallow and mount wrappers. This is a reasonable public API to have, and chai-enzyme needs this for a couple of things.
=> Add public root method

packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-test-suite/package.json, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/_helpers/react-compat.js
Found this corner case bug using the Airbnb test suite. Apparently there is some slightly different internal structure that gets created when mounting on top of existing HTML markup. This adds tests for that and fixes it for the 15 and 15.4 adapters.
=> Fix hydrating renders for React 15 adapters

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js, packages/enzyme/src/selectors.js
This appears to have been introduced by #1086 
Surprisingly, we didn't have any unit tests verifying this functionality. This PR fixes the bug and adds a test.
Fixes #1130
=> Support nested/multiple find calls

docs/api/ShallowWrapper/equals.md, docs/api/selector.md, package.json, packages/enzyme-adapter-react-13/src/ReactThirteenElementToTree.js, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme/package.json, packages/enzyme/src/RSTTraversal.js, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js, packages/enzyme/src/selectors.js
Fixes #656.
This PR ensures `null` and `undefined` props are skipped when comparing nodes:
```js
expect(nodeEqual(
<div className={null} id={undefined} />,
<div />
)).to.equal(true);
```
A helper function `cleanProps` removes all `null` and `undefined` props. I wanted to do that in `propsOfNode()`, but there are multiple `return` statements, which would result in a lot of repetition.
Let me know if this PR needs modification or anything else ;)
=> Skip undefined props when comparing nodes

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js
There is a discussion in #678 about this.
If enzyme chooses this option, the time has come.
I think this PR needs more works, which are tests and documentation.
Does enzyme enable lifecyleExperimental by default at v3?
=> Breaking: lifecycleExperimental by default

docs/installation/react-16.md
ES5 configuration proposed originally basically doesn't work.
We're requiring 'enzyme' as Enzyme, but using configure() method out of nowhere:
```js
var Enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-16');
configure({ adapter: new Adapter() });
```
I derived my variant from the original ES6 version and it works fine for me:
```js
var enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-16');
enzyme.configure({ adapter: new Adapter() });
```
Need it specifically for the .babelrc `["env", { "modules": false }]` case.
=> ES5 setup file correction

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-react-16/src/findCurrentFiberUsingSlowPath.js, packages/enzyme-test-suite/test/Adapter-spec.jsx
I added a test relative to https://github.com/airbnb/enzyme/issues/1163#issuecomment-332438576
I tried to fix it but I couldn't figure out when to use alternate node.
=> Fix node resolving in React 16 adapter

docs/installation/react-013.md, docs/installation/react-014.md, docs/installation/react-15.md
**react-013.md**
ES5:
```js
// setup file
var enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-13');
enzyme.configure({ adapter: new Adapter() });
```
**react-014.md**
ES5:
```js
// setup file
var enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-14');
enzyme.configure({ adapter: new Adapter() });
```
**react-15.md**
ES5:
```js
// setup file
var enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-15');
enzyme.configure({ adapter: new Adapter() });
```
`react-16.md` already fixed in the previous merged pull request: https://github.com/airbnb/enzyme/pull/1194
=> ES5 docs fix: enzyme.configure()

docs/guides/jest.md
The url was broken since the `/en/` directory was missing from it's path.
=> Fixed Jest docs url

docs/installation/react-014.md, docs/installation/react-15.md, docs/installation/react-16.md, packages/enzyme-adapter-react-14/package.json, packages/enzyme-adapter-react-15.4/package.json, packages/enzyme-adapter-react-15/package.json, packages/enzyme-adapter-react-16/package.json
This addresses #1161 . It makes react test renderer a regular dependency instead of a peer dependency so that users do not have to install it themselves. They should not have to because they don't use it directly.
This is safe because the test renderer does not have a dependency on react, so there will be no second copy. It has a peer dependency, and as long the version of test renderer that is installed has its peer dependency satisfied, everything should be fine.
=> Make react-test-renderer a dependency instead of a peer dependency

docs/installation/react-014.md, docs/installation/react-15.md, docs/installation/react-16.md, packages/enzyme-adapter-react-14/package.json, packages/enzyme-adapter-react-15.4/package.json, packages/enzyme-adapter-react-15/package.json, packages/enzyme-adapter-react-16/package.json
making these explicit dependencies will make it easier for other
projects and packages that allow for multiple versions of react
=> move react-addons-test-utils to dependencies

docs/api/selector.md
Updates Selector documentation to explicitly explain `key` and `ref`, use proper CSS selector terminology, and re-organize to better differentiate from CSS-based selectors and React Prop Selectors.
=> increase clarity of Selector documentation

docs/installation/react-014.md, docs/installation/react-15.md, packages/enzyme-adapter-react-14/package.json, packages/enzyme-adapter-react-15.4/package.json, packages/enzyme-adapter-react-15/package.json
Fix #1277 by reverting the portions of #1252 that affected react 14, 15, and 15.4. React-test-renderer/react-addons-test-utils will again be a peer dependency for those versions.
Leaving react 16's test renderer as a regular dependency because they changed their versioning scheme for 16 so it should be safe (see https://github.com/facebook/react/issues/11278).
=> revert peer dependency change for react-test-renderer 14, 15, and 15.4

docs/api/ShallowWrapper/setProps.md
Super minor wording change - I was just referencing these docs, and the use of "state" here confused me for a second.
=> Update setProps.md: misleading "state" -> "props"

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
@ljharb @lelandrichardson This is to fix #1247 🙏 
Currently, componentDidUpdate is not called when calling setState with React v16.
=> Fix to call componentDidUpdate on setState of React v16

CONTRIBUTING.md, docs/api/shallow.md
Removes lifecycleExperimental from ShallowWrapper docs.
~~Updates code throwing an error when this option is used.~~
~~Updates related unit tests.~~
Updates CONTRIBUTING doc.
=> [lifecycleExperimental] Issue #1303

packages/enzyme-test-suite/test/RSTTraversal-spec.jsx, packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme/package.json, packages/enzyme/src/Utils.js, packages/enzyme/src/selectors.js
* Adds support for all attribute selector operators
* Removes `nodeHasProperty` in favor of `nodeHasMatchingProperty`
* Updates property/attribute tests to use the public API instead of importing the internal `nodeHasProperty` utility. This decouples the tests from the internal implementation and also makes them more robust. I discovered https://github.com/airbnb/enzyme/issues/1155 while doing this.
=> Support all attribute selector operators

env.js
`npm run react:16` fails on Windows, seem like it's trying to use the quote as part of the version
```
$ npm run react:16
> enzyme@0.0.1 react:16 C:\prj\enzyme
> npm run env -- 16
npm WARN invalid config loglevel="notice"
> enzyme@0.0.1 env C:\prj\enzyme
> babel-node ./env.js "16"
{ Error: Command failed: npm i --no-save react@'^16.0.0-0' react-dom@'^16.0.0-0'
npm WARN invalid config loglevel="notice"
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react@'16.0.0-0'
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\idan\AppData\Roaming\npm-cache\_logs\2017-11-13T00_12_18_992Z-debug.log
at …
```
=> fix env command on Windows

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/RSTTraversal.js
ReactWrapper.text() return string with the spaces as is, ShallowWrapper.text() removing double spaces and replacing &nbsp; with regular space (removing doubles as well).
=> Change ShallowWrapper.text() trim spaces with same behavior as ReactWrapper.text()

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/_helpers/react-compat.js
I’m happy to add tests, but i don’t really understand the test suite nor where the appropriate place to add them is for the v16 only feature. 
@aweary from what I can tell the Portal fiber is similar to a host component in that it’s essentially a transparent wrapper over it’s rendered children. It does hold some host container info which may be required for actual DOM traversal but in terms of the RST tree this should give an accurate representation as React sees it.
=> Add Portal support

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/_helpers/react-compat.js
This PR adds support for portals.
In making this PR, I followed the `CONTRIBUTING.md` as closely as possible. This PR essentially adds a test to the [PR](https://github.com/airbnb/enzyme/pull/1263) submitted by @jquense, who should be given credit if this PR is accepted.
I'm not too familiar with the organization of the tests, so you might wish to place the test in a different location. However, it should get the job done.
=> Support portals

docs/api/ReactWrapper/exists.md, docs/api/ReactWrapper/isEmpty.md, docs/api/ReactWrapper/isEmptyRender.md, docs/api/ShallowWrapper/exists.md, docs/api/ShallowWrapper/isEmpty.md, docs/api/ShallowWrapper/isEmptyRender.md
Corrects `.to.be(false)` to `to.be.false`
=> Fix code example in .exists() documentation

packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/RSTTraversal-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx
…e Object.
Update isIterable function to leverage getIteratorFn.
Rewrite flatten function to leverage getIteratorFn.
Add unit test for flatten function.
Add unit tests for arbitrary iterable children.
Support for Symbol.iterator and @@iterator iterables.
=> Better support for iterable children

packages/enzyme-adapter-react-helper/src/ifReact.js
This PR adds an `ifReact` entry point. The goal is to use it like this:
```js
import ifReact from 'enzyme-adapter-react-helper/build/ifReact';
describe('some stuff', () => {
ifReact('>= 14', it, it.skip)('is a test with SFCs', () => {
…
});
});
```
The reason to take a yes and a no function, instead of hardcoding it/it.skip, is so that it's not tightly coupled to mocha/jest/jasmine.
=> `enzyme-adapter-react-helper`: [New] add `ifReact`

docs/api/ReactWrapper/text.md
JSX element are stripped from returned string as far as I understand
=> Update of text.md

packages/enzyme-adapter-react-helper/package.json, packages/enzyme-adapter-react-helper/src/safeSFC.jsx
Where you’d otherwise have an SFC in tests, use safeSFC to make your tests work in React 0.13 also:
```js
const Foo = safeSFC(function Foo(props, context) {
return null;
});
const wrapper = shallow(<Foo />);
```
Static properties are copied over.
The intention was to ensure that SFCs only worked in React 0.13 *in tests*, for convenience - never in production code, to mirror actual React 0.13 usage.
Other alternatives I considered and rejected include:
- a babel transform only in test dirs (too hard to have reliable component detection)
- an alternative enzyme adapter (would be overly complex to integrate with the helper's main export, and would work for production components too)
- monkeypatching React 0.13 (nope_octopus.gif)
=> [enzyme-adapter-react-helper] [New] add `safeSFC`

packages/enzyme-adapter-react-helper/src/enzyme-adapter-react-install.js
this pr fixes an issue where if you supplied 15 as `reactVersion` to `semver.intersects(reactVersion, '^16.0.0-0')`, it would return true. This is a bug in semver.intersects and the `-0` will have to removed until it is fixed
cc @ljharb
=> patch semver range due to bug in semver.intersects

docs/guides/migration-from-2-to-3.md
I created this after being unaware of the new behaviour in an attempted upgrade.
I have added an explanation about `hostNodes` in the migration guide.
This is in response to issue #1406.
=> add selectors and hostNodes section to migration guide

docs/api/mount.md, docs/api/shallow.md
I know it was in the v3 migration guide and it is mentioned if you carefully read the docs but as a regular Enzyme user I managed to completely miss this change!
This is 100% my fault, I'm not saying otherwise, but thought this small tweak to the docs might make that clearer in case any other devs make my mistake. If you disagree feel free to close :)
=> Make it clear that shallow rendering does call lifecycle methods.

docs/api/ShallowWrapper/contains.md
This may be obvious to most, but it wasn't for me, that contains() is comparing JSX (rather than the resulting html) and therefore curly braces are required with embedded expressions.
=> Add example to contains() docs with an embedded expression

docs/guides/jest.md
Ran into confusion with install and setup when neither the Enzyme documentation nor the Jest documentation mentioned where to attach the setup file to configure the Enzyme adapter. Went searching and found [multiple](https://github.com/airbnb/enzyme/issues/1265#issuecomment-336740161) [ppl](https://github.com/facebookincubator/create-react-app/issues/3206#issuecomment-332582236) ran into this issue.
Updated the "Using Jest with Enzyme" docs to clarify this.
=> Update Readme for setup file with Jest

docs/api/ShallowWrapper/instance.md, docs/api/ShallowWrapper/props.md
Related to https://github.com/airbnb/enzyme/issues/1232
=> [Docs] Update docs around SFC instances in React 16

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
I've added a few more passing tests in [**686f31a**](https://github.com/airbnb/enzyme/pull/1410/commits/686f31a2b9a0e223d7f50eb24f158e8b7d4b5166). Based on the illustrated behaviour of both `.find` and `.contains` I assumed the behaviour of `.find` illustrated in [**46f5da8**](https://github.com/airbnb/enzyme/pull/1410/commits/46f5da83e9c2e9f1f8525e17769fc6a97d0317c6). Not sure whether this is a bug report or a feature request.
Passing:
```jsx
const Foo = () => <div />;
const wrapper = mount((
<div>
<Foo className="foo" />
</div>
));
expect(wrapper.find('Foo').type()).to.equal(Foo);
```
Not passing:
```jsx
const Foo = () => <div />;
const wrapper = mount((
<div>
<Foo className="foo" />
</div>
));
expect(wrapper.contains('Foo')).to.equal(true);
```
=> .contains() edge cases

packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/_helpers/adapter.js, packages/enzyme-test-suite/test/_helpers/setupAdapters.js, packages/enzyme/src/validateAdapter.js
=> [Fix] improve "bad adapter" error message

packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
- Convert nodes in `contains` functions to RST before comparing 
- Fixes #1422
=> [Fix] Convert nodes to RST nodes before comparing

docs/api/ReactWrapper/name.md, docs/api/ReactWrapper/type.md, docs/api/ShallowWrapper/name.md, docs/api/ShallowWrapper/type.md, docs/api/shallow.md, packages/enzyme/src/ShallowWrapper.js
Also fixes a docs typo I ran into that was replicated in a few places.
=> Add null option to shallow type() comment & docs

docs/api/ReactWrapper/contains.md
This should improve the discoverability of the function that is more often wanted.
=> Link from contains to containsMatchingElement

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
This PR is in support of https://github.com/airbnb/enzyme/issues/1149.
There are two main assumptions that I've fixed:
- in `ReactSixteenAdapter`, flatten and map over the render output if possible, instead of assuming that it is always an element
- in `ShallowWrapper`, reuse existing logic to set `NODE` and `NODES` appropriately when the root node is an array
=> Fix ShallowWrapper for array-rendering components

README.md
Since as of #1252, `enzyme-adapter-react-16` has `react-test-renderer` as a dependency rather than a peer dependency, so users of enzyme no longer need to manually install it.
=> [Docs] Update list of enzyme-adapter-react-16 peer dependencies

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
Fixes #1488 by checking if a key is undefined, and if so, returning null.
Without the code changes, the new tests will fail with errors like this
`AssertionError: expected undefined to equal null`
=> return null for missing keys

docs/guides/migration-from-2-to-3.md
Was going through the 2 to 3 migration guide, and saw some unhighlighted blocks of syntax.
=> setting jsx highlighting on certain blocks (migration docs)

docs/api/ReactWrapper/mount.md, packages/enzyme/src/ReactWrapper.js
=> Make clearer the docs for .mount()

packages/enzyme-test-suite/test/Debug-spec.jsx, packages/enzyme/src/Debug.js, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
This implements `.debug({verbose: true})` which prevents boxing primitive values when stringified.
Fix for #1476
=> Implement verbose debug output

packages/enzyme-adapter-react-helper/package.json
Upgrading npm-run to pick up this security fix: https://github.com/timoxley/npm-run/pull/17
Security advisory: https://nodesecurity.io/advisories/310
Tested locally
=> Upgrading npm-run to pickup security fix

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
In Enzyme v3, I saw many issues about changes that we have to call `update()` after `instance.setState()`.
Actually, `wrapper.update()` doesn't rerender even though the name implies to update something.
`wrapper.update()` only does to get a latest ReactElementTree from ReactShallowRenderer.
I think it would be nice if developers don't care about calling `wrapper.update()`.
* https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#for-mount-updates-are-sometimes-required-when-they-werent-before
In this case, enzyme can't handle all cases that need to call `wrapper.update()`.
```js
expect(wrapper.find('p').text()).to.equal('0');
wrapper.find('.button').prop('onClick'); // Update the value to '1'
// enzyme should call wrapper.update() but enzyme can't handle that
// …
```
=> [Shallow]Call update() automatically through get querys

packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js, packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
Fix #1504 
We should pass the `ref` to the wrapped element if a root element has `ref`.
=> Fix to call ref for a root element

docs/api/ShallowWrapper/shallow.md
Fixes #762:
Added details of the following `options` parameters for `shallow` API:
- `disableLifecycleMethods`
- `lifecycleExperimental`
This should update the GitBook html documentation to include all available options:
http://airbnb.io/enzyme/docs/api/ShallowWrapper/shallow.html
=> Fixed #762: Improved shallow options documentation

packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme/src/selectors.js
Adds some initial support for pseudo selectors, There are more that could be added but before I did that I started with the few I miss the most in order to get some feedback
=> Add support for some pseudo selectors

docs/api/ShallowWrapper/prop.md
It was not immediately obvious to me that if `.prop(key)` returned a function,  that you could pass that function parameters and test the effect of calling the function with those parameters. I hoping this would help make that possibility more clear to other React testing newbies.
=> .prop(key w/ child component of wrapper and func

docs/api/shallow.md
It's important for the users to know that they need to import the component. Since after rendering React component , they turn into html tags.
=> You need to import the component

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
Fix #1602
This PR is to support `getSnapshotBeforeUpdate` on shallow.
I've added `supportGetSnapshotBeforeUpdate` flag into `ReactSixteenAdapter` to implement this.
As a result, `getSnapshotBeforeUpdate` is called even if you use `react-test-renderer@<16.3.0` so we have to add a new adapter like `enzyme-adapter-react16.2` that turn off `supportGetSnapshotBeforeUpdate`.
You might think `getSnapshotBeforeUpdate` should be called before `render`, but the order is same as `react-dom`.
https://codepen.io/koba04/pen/erbbvB?editors=0011
React calls `getSnapshotBeforeUpdate` at commit phase and call `render` at render phase so when `getSnapshotBeforeUpdate` is called `render` has already been called.
```
〜 render phase 〜
Call render
〜 commit phase 〜
Call getSnapshotBeforeUpdate
Update host …
```
=> Add getSnapshotBeforeUpdate support into shallow

packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme/src/selectors.js
Right now `.find('#foo ~ #bar')` will throw an error if `#foo` matches the root element.
This PR adds test and the missing parent check that caused the problem.
=> Bugfix for using general sibling selector on root

docs/api/ReactWrapper/exists.md, docs/api/ShallowWrapper/exists.md, docs/api/mount.md, docs/api/shallow.md, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
This PR makes `.exists` optionally take a selector, in which case it will delegate to `.find(selector).exists()`.
=> Make `.exists` take optional selector

packages/enzyme/src/selectors.js
These were found while diagnosing #1680 .
Corrected typos, minor refactor to avoid reusing a variable for two different purposes.
=> Typos & minor update in selectors.js

packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js
This PR is to follow up https://github.com/airbnb/enzyme/pull/1133#discussion_r140950790
=> Implement spyMethod and use it to inspect the result of shouldComponentUpdate

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/_helpers/untranspiledSloppyReturnThis.js
This works around a bug in `react-test-renderer`: https://github.com/facebook/react/issues/13141
This seems to only be an issue in react 16, and only when using `shallow`.
In the future, when that bugfix is published, i'll remove this fix and bump the minimum required version.
=> react 16: `shallow`: SFCs do not get a `this`

packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/Utils-spec.jsx
Adding support for css3 animation events:
- [animationstart](https://developer.mozilla.org/en-US/docs/Web/Events/animationstart)
- [animationiteration](https://developer.mozilla.org/en-US/docs/Web/Events/animationiteration)
- [animationend](https://developer.mozilla.org/en-US/docs/Web/Events/animationend)
The support for these events in React's documentation can be found [here](https://reactjs.org/docs/events.html#animation-events)
=> Add event name mapping for animation events

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
When I traverse through React components in a mounted tree, it can't find parent and fails with the error
```
TypeError: Cannot read property 'reverse' of null
at parentsOfInst (src/MountedTraversal.js:255:10)
at ReactWrapper.<anonymous> (src/ReactWrapper.jsx:623:35)
at ReactWrapper.single (src/ReactWrapper.jsx:916:21)
```
See added test as a reproduction example.
As far as I could track, it happens, because the node can't find itself because component wrapper the wrong children `wrapper.children()` in this test returns an empty array, however we have a node inside.
=> Add tests on broken .parent() use-case

docs/api/ReactWrapper/detach.md, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme/src/Utils.js
Fixes #1316
Reviewers: please help ensure that the following scenarios will work after this PR:
- new enzyme + new adapter
- new enzyme + old adapter
- old enzyme + new adapter
=> [enzyme-adapter-react-16] [New] `mount`: add `hydrateIn` option

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
This pull request adds a test for the issue https://github.com/airbnb/enzyme/issues/1475 but doesn't fix it.
=> Add failing .at(0).exists() test

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
Fix for https://github.com/airbnb/enzyme/issues/1628
=> #1628 - componentWillReceiveProps() receives undefined instead of default

packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js, packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16/package.json, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/package.json, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/Debug-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme-test-suite/test/_helpers/react-compat.js, packages/enzyme-test-suite/test/adapter-utils-spec.jsx, packages/enzyme/src/Debug.js, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js, packages/enzyme/src/selectors.js
Required for #1592 to work properly, still in progress but i want to make sure the proposed API changes to adapters are ok before i polish up all the tests and what not
cc @ljharb
=> Add additional type checks to adapters

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
=> [New] `shallow`: `setProps`: add callback argument

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/RSTTraversal.js, packages/enzyme/src/selectors.js
This fixes #1664 by altering `childrenOfNode()` in `RSTTraversal` to return (recursively if needed to accommodate nesting) the children of any node it encounters that is a Fragment instead of the Fragment element. It additionally updates `matchAdjacentSiblings()` and `matchGeneralSibling()` to make use of `childrenOfNode()` instead of looking directly at `parent.rendered` in order to make use of the new Fragment logic, which lives inside of the `ReactSixteenAdapter`'s `isFragment()`
Consider the following example
```jsx
const FragmentExample = () => (
<div className="container">
<React.Fragment>
<React.Fragment>
<span>A span</span>
</React.Fragment>
</React.Fragment>
</div>
);
```
Calling `const wrapper = mount(<FragmentExample />);` will yield a wrapper with the following structure: …
=> Adding Fragment support for shallow `.find` and `.findWhere`

docs/api/mount.md, docs/api/shallow.md
Match the signature as expressed in`setProps.md`
=> [DOCS] Add callback arg to setProps header in mount.md

docs/guides/migration-from-2-to-3.md
The migration guide does not currently include any information on how to migrate tests that rely on the enzyme 2 behavior for `ref(refName)`
=> Provide migration instructions for `ref(refName)`

CONTRIBUTING.md
* Explains that the test suite & linter run on built Enzyme
* Adds guidance on dev workflow (as per recommendation in #1173)
=> Clarify dev workflow in CONTRIBUTING.md

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
Currently, the other tests except `merging props` don't run by `npm run test:only`.
I guess that `describe.only` intend to avoid failing by `should call componentWillReceiveProps for new renders` so I've skiped the test.
https://travis-ci.org/airbnb/enzyme/jobs/413839140
=> fix to run all tests in ShallowWrapper-spec.jsx

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
Fix #1452
This is not an ideal fix, but works 😅 
(This PR is based on #1741 to run all tests)
=> Fix to call cDU when an instance calls setState

packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme/src/selectors.js
Given a node like:
```html
<div className="test">
<div></div>
</div>
```
a selector like `.find(".test div")` or `.find("div div")` unexpectedly matches the outer div, as well as the inner div.
The patch uses child nodes of current matches, which excludes the 'parent' match.
=> Fix descendant selector

packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx
Fixes #1719.
Reviewers, please check these claims:
- using the new adapter-utils package, but old adapters, will quietly lack pointer events support
- using the old adapter-utils package, but new adapters, will quietly lack pointer events support
- using new everything will have pointer events support
=> [New] add pointer events support

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
=> [Fix] `shallow`: `.setState()`: stub out `setState` on non-root code paths as well.

docs/api/ReactWrapper/simulate.md, docs/api/ShallowWrapper/simulate.md
Address issue #1748 and shine some light on how and when to pass a mock event when using .simulate() with ShallowWrapper or ReactWrapper.
=> [Docs] Update clarifying event object passed to .simulate()

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
Fixes #1766. Fixes #1765.
I missed that ShallowWrapper's constructor is called when finding child components.
In this case, the `renderer` is a `renderer` of the root, which means its `instance` is the instance of the root component. So `cDM` of the instance is called when creating a ShallowWrapper instance for child components.
=> Fix to call unexpected cDM

packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
React 16+ adapters `toTree` given a `HostPortal` returns a portal wrapping the child tree, instead of returning the child tree directly. This lets Portals show up in debug output and be found. Added the portal wrapper with a `nodeType` of `'portal'` and a `type` of react-is `Portal`.
=> Mounted portals show in debug and can be found

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
- Remove duplicate `should find elements through portals` test
- Move `.find` portal tests to be together
- Switch `.find` portal tests to count results instead of using debug output (matches tests in `ShallowWrapper-spec`)
=> Modify portal mount tests

packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/Utils.js
Remove some `Utils` changes that were added in https://github.com/airbnb/enzyme/pull/1760, as this logic is reflected instead in the adapters (added in https://github.com/airbnb/enzyme/pull/1761).
This should have no functional changes
=> Remove portal specific logic from utils

packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Adapter-spec.jsx
Add `children` to mounted portal `props`. This brings the mount results in line with the shallow results and the other element types (which have `props.children`).
Also added the `shallow renders react portals` test. Compared to the `renders react portals` test above, `node.rendered.ref` comes back `undefined` instead of `null` which may be an issue with https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js#L103, if a portal can never have refs this might make sense to hard code as `null`. The inner divs `rendered` also comes back ` 'Hello World!'` instead of `['Hello World!']` which seems like the shallow renderer `Utils.elementToTree` is missing the check at https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/sr …
=> Add children to mounted portal props

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
=> Shallow rendering, setState after setProps calls componentWillReceiveProps

packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
Fix #1783 
This PR makes to prevent updates when setState returns `null` or `undefined`.
But the callback of setState's 2nd arguments should always be called as well as a behavior of ReactDOM.
=> Fix to skip updates when nextState is null or undefined

packages/enzyme-test-suite/package.json, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/_helpers/react-compat.js, packages/enzyme/src/ShallowWrapper.js
Fix https://github.com/airbnb/enzyme/issues/1784#issuecomment-414902941
=> Fix to prevent updates with PureComponent

packages/enzyme-adapter-react-16/package.json, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-react-16/src/detectFiberTags.js, packages/enzyme-adapter-react-16/src/findCurrentFiberUsingSlowPath.js
This removes Enzyme's reliance on internal React reconciler constants which can change between releases (and *are* going to change in 16.4.3 which we plan to cut on Monday).
Instead, we're feature testing to detect the Fiber tags. The fields I'm relying on are relatively stable, and are expected to stay significantly more stable than the constants. The detection is done lazily (because we can't assume the DOM is available until you call `mount`). I've checked that other code paths don't use `FiberTags`.
This should work with all 16.x versions. I did some manual checking with 16.1, 16.2, 16.3, and the master React version (which would break without this). I haven't verified 16.0 but I'd expect it to work as well.
I included the revert of the reconciler dependency. This is because the code …
=> Detect Fiber types to avoid inlining constants

docs/guides/jest.md
while navigating from [Guides](http://airbnb.io/enzyme/docs/guides.html) page.
=> incorrect title companred to parent link

docs/api/ReactWrapper/setContext.md, docs/api/ReactWrapper/setState.md, docs/api/ShallowWrapper/setContext.md, docs/api/ShallowWrapper/setProps.md, docs/api/ShallowWrapper/setState.md
This PR addresses issue #1788
---
Update the documentation of ShallowWrapper/setProps to reflect that the method accepts a callback as its second argument.
=> [Docs] setProps accepts a callback as its second argument

packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js
We haven't quite yet upgraded to react 16.4 and with 16.3 Profiler is not defined, meaning that any react nodes without a type (like a function) in shallow get serialized as `<Profiler/>`
Its not that important but I thought it could happen in the future, so I did a small refactor to not match undefined and undefined.
=> Show functions and not <Profiler/> with react 16.3

packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Debug-spec.jsx
=> [enzyme-adapter-react-{16,16.3}] [fix] `forwardRef`: respect `.displayName`

SUMMARY.md
Adding it to the Full DOM Rendering section in Summary this time.
=> Add getDOMNode to Table Of Contents

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js
Fixes https://github.com/airbnb/enzyme/issues/1809
Note that
```js
it('rerenders on an error during render', () => {
const wrapper = mount(<ErrorBoundary spy={sinon.stub()} />);
expect(wrapper.find({ children: 'HasThrown' })).to.have.lengthOf(0);
expect(wrapper.find({ children: 'HasNotThrown' })).to.have.lengthOf(1);
return new Promise((resolve) => {
wrapper.setState({ throws: true }, () => {
expect(wrapper.find({ children: 'HasThrown' })).to.have.lengthOf(1);
expect(wrapper.find({ children: 'HasNotThrown' })).to.have.lengthOf(0);
resolve();
});
});
});
```
Will still fail, I will fix that separately.
@ljharb
=> Add update after simulateError

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
Fixes the tests in https://github.com/airbnb/enzyme/pull/1781.
There are a few alternative ways to do fix those tests (and some things wrong with this one)
Solution 1 - This one! Save the original `ROOT` node tree, and use in calls to `parents` etc
- The saved root node tree will not actually match the `ROOT` node tree after root `update`. `update`s will affect the `ROOT` node tree but not the saved tree. This is already sort of the case, currently updates to the `ROOT` (for example setting state) would not affect `childWrapper[NODES]`, but would modify `childWrapper[ROOT][NODES]`. Given that we want child wrappers to be immutable I think this might make the most sense.
- It is possible here for something to still accidentally compare between the old and new tree by using …
=> Freeze ROOT_NODES for child wrappers

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/RSTTraversal.js, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
Fixes #1780.
These tests are failing; anyone who can help by posting a link to their branch would be very appreciated.
=> [Fix] `shallow`: `.parents`: ensure that one `.find` call does not affect another

docs/guides/jest.md
Update the doc to add reference link to the setup files. It might not be clear as to what `setup file` means if readers read the jest section before the installation section.
Also propose a minor wording change.
=> Update docs for setting up with jest

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js
=> [New] `mount`: `.state()`/`.setState()`: allow calling on children

packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme/src/Utils.js
Fixes #1830
Other: 
- Added Utils.isCustomComponentElement tests
- Pass test:all
- Pass lint
=> [fix] `shallow`: A nested ForwardRef is not recognized as a valid component by `dive()`

docs/api/mount.md
According to the [docs on `ReactWrapper.ref`](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/ref.md) the method returns either a `ReactComponent` or an `HTMLElement`. This is inconsistent with the docs for `mount`. Testing shows that the docs on `ReactWrapper.ref` are corrected, so I've updated the `mount` docs to match.
=> Update ReactWrapper.ref docs with correct type

docs/guides/jsdom.md
Update JSDOM docs to include simple timeout-based polyfills for `{request|cancel}AnimationFrame` as react requires those.
=> [doc] Update JSDOM docs to include {request|cancel}AnimationFrame polyfills

docs/guides/jsdom.md, docs/guides/react-native.md, packages/enzyme-example-mocha/test/.setup.js
As discussed in #1375, I was also unable to get React Native testing working with Jest/Enzyme with the current documentation instructions.
I see that a React Native adapter is still being discussed in #1436, but I found that some users have had success with jsdom. I was able to get both react-native-mock-renderer and jsdom working, but react-native-mock-renderer didn't result in very clear snapshots when using Jest snapshot testing.
I have therefore provided some instructions here for how I was able to get React Native testing working with jsdom, and I added some examples from the [React Native boilerplate project](https://github.com/ProminentEdge/mobile-boilerplate) where it is currently working. I decided to leave in a few helpful tips of other issues I encountered along the way as …
=> Documentation update for testing React Native using jsdom

docs/api/ReactWrapper/props.md, docs/api/ShallowWrapper/prop.md, docs/api/ShallowWrapper/props.md
changed typo 'validNumber..' to 'validateNumber...'
=> typo in .prop(key)

docs/api/ReactWrapper/renderProp.md, docs/api/ShallowWrapper/renderProp.md, docs/api/mount.md, docs/api/shallow.md, packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js, packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-adapter-utils/src/wrapWithSimpleWrapper.jsx, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
Adds a `renderProp` method to `ShallowWrapper`s to ease testing render props.
This PR basically extracts `renderProp`  out of [@commercetools/enzyme-extensions](https://github.com/commercetools/enzyme-extensions). We would deprecate and drop it there if `renderProp` makes it into `enzyme` itself.
I wrote [this article](https://medium.com/@dferber90/test-a-render-prop-6a44e02f4c39) a while ago detailing how to use `renderProp` and why.
I'm curious for feedback of whether you'd want to accept it or not after some interest was shown in https://github.com/commercetools/enzyme-extensions/issues/8.
---
Thanks to @tdeekens who helped set up and bounce ideas back&forth with for `renderProp` in `enzyme-extensions`!
Closes #1444. Related to #1856.
=> Add renderProp to ShallowWrapper

docs/api/ReactWrapper/renderProp.md, docs/api/ShallowWrapper/renderProp.md, docs/api/mount.md, docs/api/shallow.md, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
This PR changes the `renderProp` API as described in https://github.com/airbnb/enzyme/pull/1863#issuecomment-436175166.
This is merely a suggestion at the moment and I'm happy to close it again if we settle on another approach or even keep the current one.
The motivation for "returning a function" is that the arguments to enzyme's `renderProp` won't get mixed with the arguments to the render prop function itself. This allows us to eventually add more options (like context) which we can apply to the newly created wrapper.
An example usage (formatted with Prettier) would look like this:
```jsx
const wrapper = shallow(<App />)
.find(Mouse)
.renderProp("render")(10, 20)
.find(Mouse)
.renderProp("foo")(3, {
long: {
yeah: true
}
})
.find(Bar)
.renderProp("x")();
```
At this point, one might …
=> Change renderProp API

docs/guides/migration-from-2-to-3.md
Hi there,
In my team, we are currently going through your migration guide to update from Enzyme 2 to 3 (very handy btw 👍) and we noticed one of the links is broken for `.hostNodes()`.
We have opened a PR fix for this to distract us away from the pain we are going through with other packages for not upgrading sooner 🙈 
Cheers.
Jack
=> Updated broken link for “.hostNodes()” in migration guide

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
- Adds specs for wrapping zero nodes with `getDOMNode`, `dive`, and `name!`.
- Modifies the warning language to better accommodate zero nodes:
```
Method x is only meant to be run on a single node. 2 found instead.
Method x is only meant to be run on a single node. 0 found instead.
```
becomes
```
Method x is meant to be run on 1 node. 2 found instead.
Method x is meant to be run on 1 node. 0 found instead.
```
=> Zero-node specs and warning message

docs/api/ShallowWrapper/get.md
Thank you all guys for all this awesome work. ✌️
This Pull Request fixes a small issue I've just noticed. Since `ShallowWrapper#get` returns a `ReactElement`, we should be using `props` rather than `props()` on the demo.
=> [Docs] ShallowWrapper#get: fixed wrong `props()` usage

docs/api/ShallowWrapper/dive.md
Add a NOTE line in docs of `.dive()` about it would throw error under some cases.
See #1798
=> [Docs] Add a NOTE line in docs of `.dive()` about it would throw error

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js
=> Update: Adds recursive check for isEmptyRender

docs/api/ShallowWrapper/instance.md
According to [docs](https://airbnb.io/enzyme/docs/api/ShallowWrapper/instance.html#), calling `instance()` on a wrapped stateless component should return null (if using React 16.x)
=> Fixes confusing test description on React 16.x

packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme/src/selectors.js
Try to implement #1709 by compare `document.activeElement` and host DOM node of rst node. Work with DOMElement and component element.
Note that this only works with `mount`, not works with `shallow`. Also it won't work with simulate:
```javascript
const wrapper = mount(<input type="text" />)
wrapper.simulate('focus')
// will print false
console.log(wrapper.is(":focus"))
```
I've tested this with jsdom@6 (in test suite), 13 and 12.
=> support :focus pseudo selector in mount

packages/enzyme-adapter-react-13/package.json, packages/enzyme-adapter-react-14/package.json, packages/enzyme-adapter-react-15.4/package.json, packages/enzyme-adapter-react-15/package.json, packages/enzyme-adapter-react-16.1/package.json, packages/enzyme-adapter-react-16.2/package.json, packages/enzyme-adapter-react-16.3/package.json, packages/enzyme-adapter-react-16/package.json, packages/enzyme-adapter-react-helper/package.json, packages/enzyme-adapter-utils/package.json, packages/enzyme-example-mocha/package.json, packages/enzyme-test-suite/package.json, packages/enzyme/package.json
I started getting tired of seeing the red x next to my builds so I decided to figure out why the linter was failing. Lo and behold, @ljharb fixed the issue in `eslint-plugin-react` a few days ago!
It looks like you upgraded the dependency in the top-level `package.json`, but not in the child packages, so I figured I'd help you out with that chore.
P.S. I believe it is also a common monorepo pattern to only declare `devDependencies` in the top-level `package.json`. We could also move to that pattern to avoid chores like this in the future.
=> Upgrade eslint-plugin-react in packages

packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/adapter-utils-spec.jsx
Fixes #1590 
In `react-test-renderer@16.0 - 16.2` there's an issue where `context` is not filtered to a component's `childContextTypes`. This issue is not present in `react-test-renderer@<16` or `react-test-renderer@>=16.3`. This PR implements the same fix as `react-test-renderer@16.3` for enzyme adapters using `react-test-renderer` that have the issue.
=> Filter legacy context on childContextTypes when necessary

packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js, packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/adapter-utils-spec.jsx, packages/enzyme/src/ShallowWrapper.js
Fixes #664
This PR adds support for `getChildContext()` when shallow-rendering. I've decided to only implement parent-based context, not owner-based context (as I'm not exactly sure what that behavior is, tbh) which means I've excluded `react@0.13` from this implementation. (Hope that's okay!)
In `react@<=15`, the react shallow renderer actually calls `getChildContext()` for us! This means, as is the case with `shouldComponentUpdate()`, we just spy on that method's return value.
In `react@>=16`, `getChildContext()` is _not_ called (understandable—it's a deprecated API), so we have to call it ourselves.
P.S. Sorry the diff is a little ugly. I ended up messing with the nesting of some conditionals to avoid duplicated checks.
=> Support getChildContext() in shallow render

packages/enzyme-test-suite/test/RSTTraversal-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/RSTTraversal.js
- Add a `findWhere` test case that replicates the use case I ran into
- Update `RSTTraversal.treeForEach` to not call `fn` on empty strings
- Update `treeForEach` test case that references empty strings
In the event that the DOM has an empty string, make sure `findWhere` can iterate past it and still find elements that are further down the tree.
- Fixes #1994
- [Codesandbox](https://codesandbox.io/s/jp4vnqy2n3?expanddevtools=1&module=%2Fsrc%2FHello.js&previewwindow=tests) that replicates the initial issue I had
=> Make sure findWhere doesn't get stuck on empty string

packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/RSTTraversal.js, packages/enzyme/src/ReactWrapper.js
In order to resolve Issue #1799 and return expected .text() and .html() results for non-wrapped Fragments, nodeToHostNode in the react adapters needed to be able to handle arrays. This PR does that, changing `.text()` and `.html()` to deal with an array of nodes while maintaining backwards compatibility for adapters returning single nodes.
Fixes #1799.
=> Make nodeToHostNode handle arrays

docs/guides/jest.md
Change deprecated `setupTestFrameworkScriptFile` to `setupFilesAfterEnv`.
see: https://jestjs.io/docs/en/configuration#setupfilesafterenv-array
=> Update deprecated key in documentation

docs/guides/jest.md
Per https://jestjs.io/docs/en/configuration#setupfilesafterenv-array, `setupTestFrameworkScriptFile` has been renamed to `setupFilesAfterEnv`, so updating these docs.
=> docs: update Jest to setupFilesAfterEnv

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-react-16/src/detectFiberTags.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
This is based on and fixes #1875.
=> Added support for React.memo

docs/guides/react-native.md
Per[ jest docs](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array), `setupTestFrameworkScriptFile` has been renamed to `setupFilesAfterEnv`
=> Update deprecated jest config key in docs

docs/api/render.md
I wasn't clear on what the API was for a wrapper returned from using `render` so I thought this might be helpful.
=> [docs] add link to Cheerio API and another example

packages/enzyme-adapter-react-13/.eslintrc, packages/enzyme-adapter-react-14/.eslintrc, packages/enzyme-adapter-react-15.4/.eslintrc, packages/enzyme-adapter-react-15/.eslintrc, packages/enzyme-adapter-react-16.1/.eslintrc, packages/enzyme-adapter-react-16.2/.eslintrc, packages/enzyme-adapter-react-16.3/.eslintrc, packages/enzyme-adapter-react-16/.eslintrc, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-react-helper/.eslintrc, packages/enzyme-adapter-utils/.eslintrc, packages/enzyme-test-suite/.eslintrc, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
This PR wrap the render function of mount renderer with `act()` so that use cases with `useEffect` would work. The test is the test case in https://github.com/threepointone/react-act-examples/blob/master/README.md#effects .
=> Wrap mount renderer render with reactTestUtils.act()

packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/package.json, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js
Prevent forgetting PR for #1970 😓  . I've added test case in this PR(should fail now).
Wait for release of facebook/react#14613 and we can update react-test-renderer in dependency.
Fixes #1970.
=> [Fix] `shallow`: ensure SCU is called after GDSFP returns null

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js
refs https://github.com/airbnb/enzyme/issues/2046
=> [enzyme-adapter-react-16] fix import

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js
Latest version of 1.11.0 throw error:
```
Cannot find module 'react-test-renderer/package' from 'ReactSixteenAdapter.js'
```
Fixes #2046
=> Fix 'react-test-renderer/package' not found

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
=> [TEST] Regression on CDU on setProps on shallow wrapped component

docs/api/ShallowWrapper/hasClass.md, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js
When `className` is regexp raises the issue in `packages/enzyme/src/ShallowWrapper.js` on the line 1256 
```
TypeError: className.indexOf is not a function
```
=> bugfix: fix error in hasClass when className is regex expression

docs/api/ReactWrapper/simulateError.md, docs/api/ShallowWrapper/simulateError.md, env.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
This PR adds support for `static getDerivedStateFromError`.
=> Support getDerivedStateFromError

docs/guides/react-native.md
=> Add on the fly JSDOM include example with react-native

packages/enzyme-adapter-utils/package.json, packages/enzyme-adapter-utils/src/wrapWithSimpleWrapper.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
=> [Fix] `shallow`/`mount`: `renderProp`: avoid warning when renderProp function returns null

.travis.yml, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/shared/methods/find.jsx
This is necessary because ReactShallowRender checks for equality in function components to decide if it should keep hooks state between renders.
This along with https://github.com/facebook/react/pull/14802 / https://github.com/facebook/react/issues/14840 should help in test components with some of the core hooks.
link #2011 , #2008 and #1996
=> Don't wrap functional components in react >=16.5 to shallow render

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/shared/methods/find.jsx
Follow up on 4149a21983fa0bdad8e5c60059add34016756d0c which attempted to fix #2038. The fix was not working for the scenario described in https://github.com/airbnb/enzyme/issues/2038#issuecomment-475204325.
This PR adds a test for the scenario above and fixes that issue.
=> [enzyme-adapter-react-16] [fix] Find memo components by constructor

packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/shared/methods/getWrappingComponent.jsx, packages/enzyme/src/ShallowWrapper.js
Fixes #1958
Fixes #1908
Fixes #1647
I think the most controversial choice I've made here is only collecting context when a `<Provider />` is the root (either because it is `.dive()ed` or passed directly to `shallow(<Provider />)`).
If we wanted to reliably make a `<Consumer />`'s `value` be that of the closest `<Provider />`, we'd need to recursively `.dive()` from the top until we find that `<Provider />`. I don't like that idea because we could end up rendering components that the end user did not want rendered.
I think, if the user _does_ want all their `<Provider />`s' values to be automatically collected, that's where `wrappingComponent` (from #1960) will come into play.
=> Add ability to dive() and shallow-render-as-root Consumers and Providers

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-react-16/src/detectFiberTags.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
Part of #2054
Opening this with failing tests. Will need to establish if we accept those for now or fix before merge. I'm also missing some context what work in `mount` is done by React and what is re-implemented in this package. 
1. [x] revert `pretest` removal
2. [x] add find by display name support
3. [x] add find by `id` support
4. [x] investigate missing timings
5. [x] prop warnings for Profiler
~I guess this is related to `Profiler` not appearing in `wrapper.debug()` output. Might be caused by `Profiler` being one of those "mode-components" (e.g. StrictMode or ConcurrentMode)~ Solved and explained in https://github.com/airbnb/enzyme/pull/2055#discussion_r272426306
These are implented in the fiber related code (ReactFiberCommitWork):
- …
=> feat: Add support for unstable_Profiler to mount API

packages/enzyme-adapter-react-16/src/detectFiberTags.js
Hello!
I'm running into an issue when using the latest version of react. 
```
Invariant Violation: Provider(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```
Turns out the context provider in `deterctFiberTags` needs to return a value.
=> fix invariant violation in provider

SUMMARY.md, docs/api/ShallowWrapper/invoke.md, docs/api/shallow.md, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/shared/methods/invoke.jsx, packages/enzyme/src/ShallowWrapper.js
cc: @kesne @alecklandgraf
This updates `ShallowWrapper#simulate()` to return the value of the executed handler if available. This allows us to easily test changes that occur in the next tick, like promise chains.
```js
// handler
onClick() {
return Promise.resolve()
.then(() => {
this.setState({ foo: true });
});
}
// test
wrapper.simulate('click').then(() => {
expect(wrapper.state('foo')).toBe(true);
});
```
=> Add ShallowWrapper#invoke() to invoke event handlers and return the handlers value

packages/enzyme-test-suite/test/_helpers/index.jsx, packages/enzyme-test-suite/test/shared/methods/props.jsx
Written the test case to test our props when there is an async handler #1872 @ljharb
Replaces #1930.
Closes #1872.
=> wrote the test case for props in async handler(new PR)

README.md
A new Preact adapter for Enzyme is available under the [Preact](https://github.com/preactjs) org on GitHub. This PR replaces the link in the README with a reference to the newer one.
This adapter supports all three Enzyme rendering modes as well as the upcoming
Preact v10 release (which is a rewrite of the internals). It also avoids an indirect dependency on React and the need to install the React-compatibility layer in order to use it.
As an aside, as part of this project some work was done to create [type definitions](https://github.com/preactjs/enzyme-adapter-preact-pure/blob/master/types/enzyme/index.d.ts) for Enzyme adapter authors to use. Would there be interest in moving those upstream into enzyme itself at some point?
=> Add link to new Preact adapter in README

packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/shared/methods/simulate.jsx
Fixes `mount(<MemoizedButton />).simulate('click')` not calling the `onClick` handler.
I strongly suspect this fixes issues with `simulate` not necessarily related to `React.memo` as well.
Alternate implementation without arrow functions and outer `this`: 9ef0776bc3fee3d539558c1ba486feb99273b223
=> Fix simulate being a no-op for memo components

docs/api/shallow.md, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-react-16/src/detectFiberTags.js, packages/enzyme-adapter-utils/src/Utils.js, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/_helpers/getLoadedLazyComponent.js, packages/enzyme-test-suite/test/adapter-utils-spec.jsx, packages/enzyme-test-suite/test/staticRender-spec.jsx
Fixes #1917 .
Given a component wrapped by `React.lazy` in `<Suspense />`
It'll plainly render a `<Lazy />` in `shallow` and render fallback component in mount.
There are something I'm not sure / still working on:
1. What should `displayName` of the component returned by `React.lazy` be? Currently I directly named it as `Lazy`. Not sure if it's something we could define by ourselves.
2. I'm trying to add an `waitUntilLazyLoaded()` on `ReactWrapper`, which will return a promise resolving when the dynamic import loaded and React trigger the re-render, so we can write some tests like:
```jsx
const LazyComponent = lazy(() => import('/path/to/dynamic/component'));
const Fallback = () => <div />;
const SuspenseComponent = () => (
<Suspense fallback={<Fallback />}>
<LazyComponent />
</Suspense> …
```
=> Support React.lazy and React.Suspense

docs/guides/migration-from-2-to-3.md
This PR has come about from this issue: https://github.com/airbnb/enzyme/issues/1299
If I have misunderstood anything please let me know.
Thanks
=> Calling `props()` after a state change should be updated to `find()`

packages/enzyme-adapter-react-helper/src/enzyme-adapter-react-install.js, packages/enzyme-adapter-react-helper/src/getAdapterForReactVersion.js, packages/enzyme-test-suite/package.json, packages/enzyme-test-suite/test/enzyme-adapter-react-install-spec.js
There's a weird issue where partial React versions can result in the wrong versions of React being installed. This happens because `semver.intersects` is returning something weird when both are true:
- A partial version of React is used - for example, 16.3
- And it's compared against a version with prerelease specifiers in it
See [this truth table](https://stackblitz.com/edit/semver-intersection-truth-table) which highlights the issue.
In this PR we:
- Separate out a function for determining the right adapter to install (which makes testing it easier)
- Convert to using `semver.satisfies` from `semver.intersects`
@ljharb , what do you think?
=> Ensure the right versions of React / adapters are installed

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
Related to #2011 .
Added `useLayoutEffect` tests with almost the same flow except that the component using `useLayoutEffect` instead `useEffect`.
The shallow test is also skipped due to https://github.com/facebook/react/issues/15275 . After that resolves we should reopen those skipped tests.
Also reset the timeout of `setTimeout` in test from `1e3` to `100` -- hope to make tests a little sooner.
=> React hooks test cases part 1 -- useLayoutEffect

packages/enzyme-adapter-react-16.1/.eslintrc, packages/enzyme-adapter-react-16.2/.eslintrc, packages/enzyme-adapter-react-16.3/.eslintrc, packages/enzyme-adapter-react-16/.eslintrc, packages/enzyme-adapter-react-16/package.json
Adds missing dependency to enzyme-adapter-react-16 – see #2124 for details.
=> Add 'has' to dependencies for enzyme-adapter-react-16

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/shared/methods/simulate.jsx
Wraps the mount simulate method in ReactTestUtils.act() to correctly
allow component interactions to be tested in a synchronous way
Fixes #2084
=> Wrap mounts simulate() in ReactTestUtils.act()

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/adapter-utils-spec.jsx, packages/enzyme-test-suite/test/shared/methods/debug.jsx, packages/enzyme-test-suite/test/shared/methods/find.jsx
=> [fix] Get correct displayName from memoized components

packages/enzyme-adapter-react-helper/src/getAdapterForReactVersion.js, packages/enzyme-test-suite/test/enzyme-adapter-react-install-spec.js
Fixes a regression caused by #2116.
If we specify `enzyme-adapter-react-install 16`, we want the latest version of the adapter supporting React 16 to be installed.
After #2116, however, we ended up getting the earliest version supporting React 16. The fix is to treat the provided version as a range (so 16 is basically `>= 16 < 17`) instead of a version (16 is `16.0.0`).
Unfortunately, pre-release versions complicates this, and this solution right now drops special handling for pre-release versions.
=> Fix adapter helper regression

docs/common-issues.md
This behavior currently is explained only in 2-to-3 version migration guide. People who never used v2 have small chance to get there. 
Since it's related to different methods and both mount/shallow suppose this file is better place for describing that.
Closes #2139.
=> explained why need to re-call .find() after update

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
Related to #2011 .
Add `useMemo` test cases in both shallow and mount test suites to make sure it works with enzyme. There are 2 tests for each:
1. In component get memoized value from `useMemo` and pass it down to child. Then rerender the component by changing a prop which is not in the dependencies of `useMemo` call. So we can assert that the prop passed down will be the same (`===`) between two rendering. Note that the memoized value is an object in the test so we can make sure they are shallow equal.
2. Like (1), but we change a prop which is in dependencies of `useMemo`, so now the prop passed down will be different between two rendering.
Any advice on additional tests is welcome :-)
=> React hooks test case part 2 -- useMemo

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
The tests are almost as same as #2144 , but for `useCallback`.
And I saw that shallow renderer doesn't memoize the callback between two rendering even the dependencies not change. So the test in https://github.com/chenesan/enzyme/commit/5cc14bacee8846bb5595936b041b66540528eeae#diff-2e9c9c89f001140a7699819fc2f5d926R1252 will fail and I temporarily skip it. Have opened an issue in react (https://github.com/facebook/react/issues/15774) . If it's confirmed as a bug of shallow renderer then I'll try to fix it in react side.
=> React hooks test case part 3 -- useCallback

docs/api/ShallowWrapper/invoke.md
The example for invoke is missing a closing set of backticks for the example which is leading to it not rendering correctly on the docs site (https://airbnb.io/enzyme/docs/api/ShallowWrapper/invoke.html).
This commit updates the code example in  `invoke.md` to include the missing backticks.
=> Add missing backticks to end of invoke example

docs/api/ReactWrapper/invoke.md, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/shared/methods/invoke.jsx, packages/enzyme/src/ReactWrapper.js
This PR expose `act` call out of `enzyme-adapter-react-16` and make the `invoke` api call handler with `act`. This will make the added test case passed without explicitly call `act()`. Before this change, we have to call `act()` outside of the `onClick` handler manually, which is easy to forget to do that.
Also update the doc of `invoke` to encourage people to trigger handler with it (so we don't need to explictly call `act()` and `update()`).
=> Wrap `.Invoke()` with act to make trigger rerender by handler less error prone

package.json, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/shared/hooks/_hook.template, packages/enzyme-test-suite/test/shared/hooks/custom.jsx, packages/enzyme-test-suite/test/shared/hooks/useContext.jsx, packages/enzyme-test-suite/test/shared/hooks/useEffect.jsx, packages/enzyme-test-suite/test/shared/hooks/useReducer.jsx, packages/enzyme-test-suite/test/shared/hooks/useState.jsx
@ljharb  @chenesan : Please review and add comments as this is my first PR. I expect some rework. Otherwise, cherrypick the commits as you said.
=> [Hooks Testing] Added Test cases for useState, useEffects & customHooks 

packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/shared/hooks/_hook.template, packages/enzyme-test-suite/test/shared/hooks/custom.jsx, packages/enzyme-test-suite/test/shared/hooks/useContext.jsx, packages/enzyme-test-suite/test/shared/hooks/useEffect.jsx, packages/enzyme-test-suite/test/shared/hooks/useReducer.jsx, packages/enzyme-test-suite/test/shared/hooks/useState.jsx
This PR adds support for [basic hooks API] (https://reactjs.org/docs/hooks-reference.html#basic-hooks) (`useState`, `useEffect`, `useContext`, related issue #1938 #1996). Currently I'm not sure what hooks API is already working in enzyme shallow / mount and what isn't, so I'll start from adding test cases to confirm the current supports. I'll try to finish the following checklist in the next few days. Also tell me if it's better to have single PR for each api :-)
I've added some test cases for `useState` and found it doesn't work in `shallow` to setState.
(Updated: Created a checklist in #2011 to try to track any issue / PR in hooks, and concentrate on support `useState` in this PR)
=> [Tests] add hooks tests

packages/enzyme-test-suite/test/shared/hooks/useEffect.jsx
Test cases written to test useState and useEffect
=> hooks testcase written

README.md
For closing #2011 . Add hooks support section in README with related shallow renderer issue link. Also add `.act()` wrap explanation.
=> Update hooks support section in README

.travis.yml, packages/enzyme-adapter-utils/src/createMountWrapper.jsx, packages/enzyme-test-suite/test/Adapter-spec.jsx, packages/enzyme-test-suite/test/Utils-spec.jsx, packages/enzyme-test-suite/test/adapter-utils-spec.jsx, packages/enzyme-test-suite/test/staticRender-spec.jsx, packages/enzyme/package.json, packages/enzyme/src/ReactWrapper.js, packages/enzyme/src/ShallowWrapper.js, packages/enzyme/src/Utils.js, packages/enzyme/src/render.js
- Fix https://github.com/airbnb/enzyme/issues/2098
- Introduce `loadCheerioRoot` util
- Use util in `render`, `mount` and `shallow`
- Added test cases in `test/staticRender-spec.jsx`
=> [Fix] `render`: handle Fiber strings and numbers

docs/api/selector.md
It is not obvious on reading through the document as-is that the CSS selector syntax works on React component names and their props. While it can be inferred through reading "The Key and Ref Props" section, that section can easily be missed when someone is specifically looking at the lists and examples of selectors to see what can be used. It is much clearer to explicitly state this syntax works on React components.
=> Explicit React CSS selector syntax description

docs/api/ReactWrapper/html.md, docs/api/ReactWrapper/isEmpty.md, docs/api/ShallowWrapper/dive.md, docs/api/ShallowWrapper/isEmpty.md, docs/api/mount.md, docs/api/selector.md, docs/api/shallow.md
On line 107, added marked `.exists()` as a code block.
=> [Docs] Mark inline code snippet in a warning in docs/api/shallow.md

docs/api/ReactWrapper/debug.md
The `options.verbose` flag was never documented for `ReactWrapper`, but was for `ShallowWrapper`. This PR copies the docs line from `ShallowWrapper` and added it to `ReactWrapper`. ✨ 
It's documented in the source code, and it seems like both wrappers use a common debug function:
https://github.com/airbnb/enzyme/blob/399db46f7eb0ea6f7067ed167493710532aabd87/packages/enzyme/src/ReactWrapper.js#L1190-L1197
=> [Docs] ReactWrapper debug: add missing option flag

packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-adapter-utils/src/createMountWrapper.jsx, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx
Fixes #2253.
After merging, this will need adapter-utils bumped and published, and then every adapter's minimum utils version bumped, and then they'll also need a publish.
=> `mount`: ensure the root’s `ref` prop gets attached to the actual root

packages/enzyme-test-suite/test/shared/methods/children.jsx, packages/enzyme/src/ReactWrapper.js
=> [Fix] `mount`: `children`: include text nodes

packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme/src/ShallowWrapper.js
=> Inherit root context information in ShallowWrapper::shallow()

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx
Resolved https://github.com/airbnb/enzyme/issues/2200
I updated `enzyme-adapter-react-16` to fix issue suspense fallback is invalid. I handled to always wrap `React.Suspense` component outside of `React.Lazy` and `React.Fallback` components in any case.
I passed all tests in master branch and local test by below code:
```js
test('renders suspenseFallback=true', () => {
const el = <ComponentWrapper />;
const wrapper = shallow(el, { suspenseFallback: true });
expect(wrapper.find(Fallback).length).toEqual(1);
expect(wrapper.find(LazyComponent).length).toEqual(0);
});
test('renders suspenseFallback=false', () => {
const el = <ComponentWrapper />;
const wrapper = shallow(el, { suspenseFallback: false });
expect(wrapper.find(Fallback).length).toEqual(0); …
```
=> Fix suspense fallback is invalid

README.md
Gitbook does not seem to support escaping pipe characters inside of a backtick code block, instead breaking the table formatting. This can be resolved by using HTML escapes and the `<code>` tag.
(Both render correctly in Github itself, which is the other place the README is viewed.)
I've tested this locally by running `yarn run docs:watch`, with the following results.
=> README: Fix adapter package compatibility table

packages/enzyme-test-suite/test/shared/methods/setProps.jsx
Added tests for componentDidUpdate and componentWillReceiveProps with setState in both shallow and mount spec.
One test is still failing in shallow denoted by todo comment and skipped test
=> [Tests] add test cases for lifecycle methods

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/Utils-spec.jsx
Fixes #2481
This is my first contribution to enzyme so happy to update/modify this PR as needed.
=> [Fix] Ensure recursive calls to displayNameOfNode uses the adapter's version of the method

packages/enzyme-adapter-react-14/package.json, packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js, packages/enzyme-adapter-react-16.1/package.json, packages/enzyme-adapter-react-16.1/src/ReactSixteenOneAdapter.js, packages/enzyme-adapter-react-16.2/package.json, packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js, packages/enzyme-adapter-react-16.3/package.json, packages/enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js, packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/shared/methods/setContext.jsx
Fixes #2258
Below are two code sandboxes that show the bug exists, i added enzyme to the sandbox when you run the tests sandbox 2 doesn't call the method while sandbox 1 does.
-  [Sandbox #1](https://codesandbox.io/s/distracted-sun-8vqh9) enzyme 3.3.0, react 16.14.0
-  [Sandbox #2](https://codesandbox.io/s/lucid-wilbur-wkotf) enzyme 3.4.0, react 16.0.0
=> Fix: setContext doesn't trigger componentWillReceiveProps 

docs/api/ReactWrapper/instance.md, docs/api/ShallowWrapper/instance.md
This updates the wording on https://airbnb.io/enzyme/docs/api/ShallowWrapper/instance.html# to account for React Hooks.
=> [Docs] Update ShallowWrapper/instance wording to account for hooks

docs/api/ShallowWrapper/prop.md
Changed variable in test. I think the previous one was wrong
=> [Docs] `shallow`: fix variable name in `prop` example

.travis.yml, packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js, packages/enzyme-adapter-react-15/src/ReactFifteenAdapter.js, packages/enzyme-test-suite/test/ReactWrapper-spec.jsx, packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, packages/enzyme-test-suite/test/selector-spec.jsx, packages/enzyme-test-suite/test/shared/methods/findWhere.jsx, packages/enzyme-test-suite/test/shared/methods/get.jsx, packages/enzyme-test-suite/test/shared/methods/getElement.jsx, packages/enzyme-test-suite/test/shared/methods/getElements.jsx, packages/enzyme-test-suite/test/shared/methods/getWrappingComponent.jsx, packages/enzyme-test-suite/test/shared/methods/html.jsx, packages/enzyme-test-suite/test/shared/methods/render.jsx, packages/enzyme-test-suite/test/shared/methods/setProps.jsx, packages/enzyme-test-suite/test/shared/methods/simulate.jsx, packages/enzyme-test-suite/test/shared/methods/text.jsx
Fixes majority of failing tests
=> Fixes: React 15.0 and 15.1

packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js, packages/enzyme-test-suite/test/shared/lifecycles/componentDidCatch.jsx
We are seeing `TypeError: Cannot read property 'displayNameOfNode' of undefined` errors and I believe I tracked it down to a regression introduced in https://github.com/enzymejs/enzyme/pull/2482. The `displayNameOfNode()` method  now references `this` but with `simulateError()` it ends up being called unbound. My fix is to just always bind `adapter.displayNameOfNode` so `this` is always `adapter`.
Thanks!
=> Fix `simulateError()` on Memo component

docs/api/ReactWrapper/update.md, docs/api/ShallowWrapper/update.md
I've noticed that the docs for `update` still say "should only be called on root", but this hasn't been the case for three years now (changed in https://github.com/enzymejs/enzyme/pull/1802).
**Side note 1**: the example in this file doesn't actually require an `update()` call. The text of the button does update just fine by itself. I played with it for some time just now, and couldn't come up with an example where an `update` call would be required. Could there have been some change recently that made `update` unnecessary?
**Side note 2**: the docs currently published on https://enzymejs.github.io/ seem outdated compared to the source code. I'm not sure what the publishing procedure would be, but I'm pretty sure I can't do it myself, because I don't have proper access.
=> [Docs] `mount`/`shallow`: `update`: Bring the docs up to date with the implementation

.github/workflows/node-pretest.yml, .github/workflows/rebase.yml
This PR bumps actions in GitHub workflow files, thus avoiding deprecation warnings.
=> Bump actions in GitHub workflow files
